import _ from 'lodash'


const getTables = () => {
    const result = {};

    result['eevc_tipo_captura'] = [
        { 'code': '1', 'name': 'Manual' },
        { 'code': '2', 'name': 'POS' },
        { 'code': '3', 'name': 'PDV' },
        { 'code': '4', 'name': 'TO' },
        { 'code': '5', 'name': 'Internet' },
        { 'code': '6', 'name': 'Leitor de trilha' },
        { 'code': '9', 'name': 'Outros' }
    ];
    result['eevc_status'] = [
        { 'code': '000', 'name': 'CV/NSU OK' },
        { 'code': '001', 'name': 'VENDA JA PROCESSADA' },
        { 'code': '002', 'name': 'MOEDA INVALIDA' },
        { 'code': '003', 'name': 'TT PREST DIF VR VD' },
        { 'code': '004', 'name': 'CV/NSU SEM VR PREST' },
        { 'code': '005', 'name': 'CP ACIMA LIM REDESHO' },
        { 'code': '007', 'name': 'CV/NSU IRREGULAR' },
        { 'code': '008', 'name': 'ESTAB BORDERO INVALI' },
        { 'code': '010', 'name': 'CARTAO EM BP' },
        { 'code': '011', 'name': 'CV/NSU SEM ASSINATURA' },
        { 'code': '012', 'name': 'CV/NSU ILEGIVEL' },
        { 'code': '013', 'name': 'CV/NSU SEM AUTORIZAÇAO' },
        { 'code': '014', 'name': 'CARTAO N CRED/DINERS' },
        { 'code': '015', 'name': 'FALTA 2A VIA PROCESS' },
        { 'code': '016', 'name': 'ESTAB S/ IATA N AUTO' },
        { 'code': '017', 'name': 'CV/NSU IRREGULAR' },
        { 'code': '018', 'name': 'CARTAO EM BP' },
        { 'code': '019', 'name': 'TX EMBARQUE VLR EXCD' },
        { 'code': '020', 'name': 'CARTAO VENCIDO' },
        { 'code': '021', 'name': 'CV/NSU PARA CARTAO JURID' },
        { 'code': '022', 'name': 'ACIMA LIMITE C/AUTOR' },
        { 'code': '023', 'name': 'DATA CV/NSU POSTERIOR RV' },
        { 'code': '025', 'name': 'CARTAO N CRED/DINERS' },
        { 'code': '027', 'name': 'CV/NSU PARA CARTAO INTER' },
        { 'code': '028', 'name': 'CARTAO EM BP' },
        { 'code': '029', 'name': 'PROMOCAO MASTERCARD' },
        { 'code': '030', 'name': 'TR INV P/TIPO CARTAO' },
        { 'code': '031', 'name': 'PLAN PAGTO BIG TICKE' },
        { 'code': '032', 'name': 'COD AUT N ENCONTRADO' },
        { 'code': '034', 'name': 'DATA CV/NSU POSTERIOR RV' },
        { 'code': '035', 'name': 'CV/NSU COM VR INCORRETO' },
        { 'code': '036', 'name': 'CV/NSU SEM AUTORIZACAO' },
        { 'code': '037', 'name': 'APRES. TARDIA CV/NSU' },
        { 'code': '041', 'name': 'PARC. INVAL.VIAC.AERE' },
        { 'code': '042', 'name': 'NAC. INVAL.- DUTY FRE' },
        { 'code': '043', 'name': 'MQ INVA/NAO TR VISTA' },
        { 'code': '044', 'name': 'CV/NSU S/JRS EM RV ROTAT' },
        { 'code': '045', 'name': 'CV/NSU ROT EM RV S/JUROS' },
        { 'code': '047', 'name': 'CARTAO N PODE PARCEL' },
        { 'code': '048', 'name': 'ESTAB. NAO AUTORIZADO' },
        { 'code': '049', 'name': 'DESCUMPRIM DE PROCED' },
        { 'code': '102', 'name': 'COD AUT N ENCONTRADO' },
        { 'code': '106', 'name': 'VR CV/NSU MAIOR QUE AUT' },
        { 'code': '108', 'name': 'AUT CARTAO DIFERENTE' },
        { 'code': '109', 'name': 'ESTAB BORDERO INVALI' },
        { 'code': '110', 'name': 'TIPO TRANS DF DA AUT' },
        { 'code': '111', 'name': 'CV/NSU SEM ASSINATURA' },
        { 'code': '112', 'name': 'CV/NSU ILEGIVEL' },
        { 'code': '114', 'name': 'CARTAO N CRED/DINERS' },
        { 'code': '115', 'name': 'FALTA 2A VIA PROCESS' },
        { 'code': '117', 'name': 'CV/NSU IRREGULAR' },
        { 'code': '125', 'name': 'CARTAO N CRED/DINERS' },
        { 'code': '137', 'name': 'APRES. TARDIA CV/NSU' },
        { 'code': '141', 'name': 'PARC. INVAL. VIAC. AERE' },
        { 'code': '142', 'name': 'NAC. INVAL. - DUTY FRE' },
        { 'code': '143', 'name': 'MQ INVA/NÃO TR VISTA' },
        { 'code': '144', 'name': 'CV/NSU S/ JRS EM RV ROTAT' },
        { 'code': '145', 'name': 'CV/NSU ROT EM RV S/ JUROS' },
        { 'code': '147', 'name': 'CARTAO N PODE PARCEL' },
        { 'code': '148', 'name': 'ESTAB. NAO AUTORIZADO' },
        { 'code': '149', 'name': 'DESCUMPRIM DE PROCED' },
        { 'code': '194', 'name': 'CV/NSU SEM AUTORIZAÇAO' },
        { 'code': '198', 'name': 'COD AUT REUTILIZADO' }
    ];
    result['eevc_bandeiras'] = [
        { 'code': '0', 'name': 'Other Flags' },
        { 'code': '1', 'name': 'MasterCard' },
        { 'code': '2', 'name': 'Diners Club' },
        { 'code': '3', 'name': 'Visa' },
        { 'code': '4', 'name': 'Cabal' },
        { 'code': '5', 'name': 'Hipercard' },
        { 'code': '6', 'name': 'Sorocred' },
        { 'code': '7', 'name': 'CUP' },
        { 'code': '8', 'name': 'Credsystem (Mais)' },
        { 'code': '9', 'name': 'Sicredi' },
        { 'code': 'A', 'name': 'Avista' },
        { 'code': 'E', 'name': 'Elo' },
        { 'code': 'B', 'name': 'Banescard' },
        { 'code': 'J', 'name': 'JCB' },
        { 'code': 'X', 'name': 'Amex' },
        { 'code': 'Z', 'name': 'Credz' }
    ];
    result['eevc_sigla_pais'] = [
        { 'code': 'AF', 'name': 'Afeganistão' },
        { 'code': 'ZA', 'name': 'África do Sul' },
        { 'code': 'AX', 'name': 'Ilhas AAland' },
        { 'code': 'AL', 'name': 'Albânia' },
        { 'code': 'DE', 'name': 'Alemanha' },
        { 'code': 'AD', 'name': 'Andorra' },
        { 'code': 'AO', 'name': 'Angola' },
        { 'code': 'AI', 'name': 'Anguilla' },
        { 'code': 'AQ', 'name': 'Antártida' },
        { 'code': 'AG', 'name': 'Antígua e Barbuda' },
        { 'code': 'SA', 'name': 'Arábia Saudita' },
        { 'code': 'DZ', 'name': 'Argélia' },
        { 'code': 'AR', 'name': 'Argentina' },
        { 'code': 'AM', 'name': 'Armênia' },
        { 'code': 'AW', 'name': 'Aruba' },
        { 'code': 'AU', 'name': 'Austrália' },
        { 'code': 'AT', 'name': 'Áustria' },
        { 'code': 'AZ', 'name': 'Azerbaijão' },
        { 'code': 'BS', 'name': 'Bahamas' },
        { 'code': 'BH', 'name': 'Bahrein' },
        { 'code': 'BD', 'name': 'Bangladesh' },
        { 'code': 'BB', 'name': 'Barbados' },
        { 'code': 'BE', 'name': 'Bélgica' },
        { 'code': 'BZ', 'name': 'Belize' },
        { 'code': 'BJ', 'name': 'Benim' },
        { 'code': 'BM', 'name': 'Bermudas' },
        { 'code': 'BY', 'name': 'Bielorrússia' },
        { 'code': 'BO', 'name': 'Bolívia' },
        { 'code': 'BQ', 'name': 'Países Baixos Caribenhos' },
        { 'code': 'BA', 'name': 'Bósnia e Herzegovina' },
        { 'code': 'BW', 'name': 'Botswana' },
        { 'code': 'BV', 'name': 'Ilha Bouvet' },
        { 'code': 'BR', 'name': 'Brasil' },
        { 'code': 'BN', 'name': 'Brunei' },
        { 'code': 'BG', 'name': 'Bulgária' },
        { 'code': 'BF', 'name': 'Burkina Faso' },
        { 'code': 'BI', 'name': 'Burundi' },
        { 'code': 'BT', 'name': 'Butão' },
        { 'code': 'CV', 'name': 'Cabo Verde Cabo Verde' },
        { 'code': 'KH', 'name': 'Camboja' },
        { 'code': 'CM', 'name': 'Camarões' },
        { 'code': 'CA', 'name': 'Canadá' },
        { 'code': 'KY', 'name': 'Ilhas Cayman' },
        { 'code': 'KZ', 'name': 'Cazaquistão' },
        { 'code': 'CF', 'name': 'República Centro-Africana' },
        { 'code': 'TD', 'name': 'Chade' },
        { 'code': 'CZ', 'name': 'República Checa' },
        { 'code': 'CL', 'name': 'Chile' },
        { 'code': 'CN', 'name': 'China' },
        { 'code': 'CY', 'name': 'Chipre' },
        { 'code': 'CX', 'name': 'Ilha do Natal' },
        { 'code': 'CC', 'name': 'Ilhas Cocos (Keeling)' },
        { 'code': 'CO', 'name': 'Colômbia' },
        { 'code': 'KM', 'name': 'Comores' },
        { 'code': 'CG', 'name': 'República do Congo' },
        { 'code': 'CD', 'name': 'República Democrática do Congo' },
        { 'code': 'CK', 'name': 'Ilhas Cook' },
        { 'code': 'KR', 'name': 'Coreia do Sul' },
        { 'code': 'KP', 'name': 'Coreia do Norte' },
        { 'code': 'CI', 'name': 'Costa do Marfim' },
        { 'code': 'CR', 'name': 'Costa Rica' },
        { 'code': 'HR', 'name': 'Croácia' },
        { 'code': 'CU', 'name': 'Cuba' },
        { 'code': 'CW', 'name': 'Curaçao' },
        { 'code': 'DK', 'name': 'Dinamarca' },
        { 'code': 'DJ', 'name': 'Djibouti' },
        { 'code': 'DM', 'name': 'Dominica' },
        { 'code': 'DO', 'name': 'República Dominicana' },
        { 'code': 'EG', 'name': 'Egito' },
        { 'code': 'SV', 'name': 'El Salvador' },
        { 'code': 'AE', 'name': 'Emirados Árabes Unidos' },
        { 'code': 'EC', 'name': 'Equador' },
        { 'code': 'ER', 'name': 'Eritreia' },
        { 'code': 'SK', 'name': 'Eslováquia' },
        { 'code': 'SI', 'name': 'Eslovênia' },
        { 'code': 'ES', 'name': 'Espanha' },
        { 'code': 'US', 'name': 'Estados Unidos' },
        { 'code': 'EE', 'name': 'Estónia' },
        { 'code': 'ET', 'name': 'Etiópia' },
        { 'code': 'FO', 'name': 'Ilhas Feroé' },
        { 'code': 'FJ', 'name': 'Fiji' },
        { 'code': 'PH', 'name': 'Filipinas' },
        { 'code': 'FI', 'name': 'Finlândia' },
        { 'code': 'FR', 'name': 'França' },
        { 'code': 'GA', 'name': 'Gabão' },
        { 'code': 'GM', 'name': 'Gâmbia' },
        { 'code': 'GH', 'name': 'Gana' },
        { 'code': 'GE', 'name': 'Geórgia' },
        { 'code': 'GS', 'name': 'Ilhas Geórgia do Sul e Sandwich do Sul' },
        { 'code': 'GI', 'name': 'Gibraltar' },
        { 'code': 'GR', 'name': 'Grécia' },
        { 'code': 'GD', 'name': 'Granada' },
        { 'code': 'GL', 'name': 'Gronelândia' },
        { 'code': 'GP', 'name': 'Guadalupe' },
        { 'code': 'GU', 'name': 'Guam' },
        { 'code': 'GT', 'name': 'Guatemala' },
        { 'code': 'GG', 'name': 'Guernsey' },
        { 'code': 'GY', 'name': 'Guiana' },
        { 'code': 'GF', 'name': 'Guiana Francesa' },
        { 'code': 'GW', 'name': 'Guiné-Bissau' },
        { 'code': 'GN', 'name': 'Guiné' },
        { 'code': 'GQ', 'name': 'Guiné Equatorial' },
        { 'code': 'HT', 'name': 'Haiti' },
        { 'code': 'HM', 'name': 'Ilha Heard e Ilhas McDonald' },
        { 'code': 'HN', 'name': 'Honduras' },
        { 'code': 'HK', 'name': 'Hong Kong' },
        { 'code': 'HU', 'name': 'Hungria' },
        { 'code': 'YE', 'name': 'Iemen' },
        { 'code': 'IN', 'name': 'India' },
        { 'code': 'ID', 'name': 'Indonésia' },
        { 'code': 'IQ', 'name': 'Iraque' },
        { 'code': 'IR', 'name': 'Irão' },
        { 'code': 'IE', 'name': 'Irlanda' },
        { 'code': 'IS', 'name': 'Islândia' },
        { 'code': 'IL', 'name': 'Israel' },
        { 'code': 'IT', 'name': 'Itália' },
        { 'code': 'JM', 'name': 'Jamaica' },
        { 'code': 'JP', 'name': 'Japão' },
        { 'code': 'JE', 'name': 'Jersey' },
        { 'code': 'JO', 'name': 'Jordânia' },
        { 'code': 'KI', 'name': 'Kiribati' },
        { 'code': 'KW', 'name': 'Kuwait' },
        { 'code': 'LA', 'name': 'Laos' },
        { 'code': 'LS', 'name': 'Lesoto' },
        { 'code': 'LV', 'name': 'Letônia' },
        { 'code': 'LB', 'name': 'Líbano' },
        { 'code': 'LR', 'name': 'Libéria' },
        { 'code': 'LY', 'name': 'Líbia' },
        { 'code': 'LI', 'name': 'Liechtenstein' },
        { 'code': 'LT', 'name': 'Lituânia' },
        { 'code': 'LU', 'name': 'Luxemburgo' },
        { 'code': 'MO', 'name': 'Macau' },
        { 'code': 'MK', 'name': 'Macedônia' },
        { 'code': 'MG', 'name': 'Madagáscar' },
        { 'code': 'MY', 'name': 'Malásia' },
        { 'code': 'MW', 'name': 'Malawi' },
        { 'code': 'MV', 'name': 'Maldivas' },
        { 'code': 'ML', 'name': 'Mali' },
        { 'code': 'MT', 'name': 'Malta' },
        { 'code': 'FK', 'name': 'Ilhas Malvinas' },
        { 'code': 'IM', 'name': 'Ilha de Man' },
        { 'code': 'MP', 'name': 'Marianas Setentrionais' },
        { 'code': 'MA', 'name': 'Marrocos' },
        { 'code': 'MH', 'name': 'Ilhas Marshall' },
        { 'code': 'MQ', 'name': 'Martinica' },
        { 'code': 'MU', 'name': 'Maurícia' },
        { 'code': 'MR', 'name': 'Mauritânia' },
        { 'code': 'YT', 'name': 'Mayotte' },
        { 'code': 'UM', 'name': 'Ilhas Menores Distantes dos Estados Unidos' },
        { 'code': 'MX', 'name': 'México' },
        { 'code': 'MM', 'name': 'Mianmar' },
        { 'code': 'FM', 'name': 'Estados Federados da Micronésia' },
        { 'code': 'MZ', 'name': 'Moçambique' },
        { 'code': 'MD', 'name': 'Moldávia' },
        { 'code': 'MC', 'name': 'Mónaco' },
        { 'code': 'MN', 'name': 'Mongólia' },
        { 'code': 'ME', 'name': 'Montenegro' },
        { 'code': 'MS', 'name': 'Montserrat' },
        { 'code': 'NA', 'name': 'Namíbia' },
        { 'code': 'NR', 'name': 'Nauru' },
        { 'code': 'NP', 'name': 'Nepal' },
        { 'code': 'NI', 'name': 'Nicarágua' },
        { 'code': 'NE', 'name': 'Níger' },
        { 'code': 'NG', 'name': 'Nigéria' },
        { 'code': 'NU', 'name': 'Niue' },
        { 'code': 'NF', 'name': 'Ilha Norfolk' },
        { 'code': 'NO', 'name': 'Noruega' },
        { 'code': 'NC', 'name': 'Nova Caledônia' },
        { 'code': 'NZ', 'name': 'Nova Zelândia' },
        { 'code': 'OM', 'name': 'Omã' },
        { 'code': 'NL', 'name': 'Países Baixos' },
        { 'code': 'PW', 'name': 'Palau' },
        { 'code': 'PS', 'name': 'Palestina' },
        { 'code': 'PA', 'name': 'Panamá' },
        { 'code': 'PG', 'name': 'Papua-Nova Guiné' },
        { 'code': 'PK', 'name': 'Paquistão' },
        { 'code': 'PY', 'name': 'Paraguai' },
        { 'code': 'PE', 'name': 'Peru' },
        { 'code': 'PN', 'name': 'Pitcairn' },
        { 'code': 'PF', 'name': 'Polinésia Francesa' },
        { 'code': 'PL', 'name': 'Polónia' },
        { 'code': 'PR', 'name': 'Porto Rico' },
        { 'code': 'PT', 'name': 'Portugal' },
        { 'code': 'QA', 'name': 'Catar' },
        { 'code': 'KE', 'name': 'Quênia' },
        { 'code': 'KG', 'name': 'Quirguistão' },
        { 'code': 'GB', 'name': 'Reino Unido' },
        { 'code': 'RE', 'name': 'Reunião' },
        { 'code': 'RO', 'name': 'Roménia' },
        { 'code': 'RW', 'name': 'Ruanda' },
        { 'code': 'RU', 'name': 'Rússia' },
        { 'code': 'EH', 'name': 'Saara Ocidental' },
        { 'code': 'AS', 'name': 'Samoa Americana' },
        { 'code': 'WS', 'name': 'Samoa' },
        { 'code': 'PM', 'name': 'Saint-Pierre e Miquelon' },
        { 'code': 'SB', 'name': 'Ilhas Salomão' },
        { 'code': 'SM', 'name': 'San Marino' },
        { 'code': 'SH', 'name': 'Santa Helena' },
        { 'code': 'LC', 'name': 'Santa Lúcia' },
        { 'code': 'BL', 'name': 'São Bartolomeu' },
        { 'code': 'KN', 'name': 'São Cristóvão e Nevis' },
        { 'code': 'SX', 'name': 'Sint Maarten' },
        { 'code': 'MF', 'name': 'São Martinho' },
        { 'code': 'ST', 'name': 'São Tomé e Príncipe' },
        { 'code': 'VC', 'name': 'São Vicente e Granadinas' },
        { 'code': 'SN', 'name': 'Senegal' },
        { 'code': 'SL', 'name': 'Serra Leoa' },
        { 'code': 'RS', 'name': 'Sérvia' },
        { 'code': 'SC', 'name': 'Seicheles' },
        { 'code': 'SG', 'name': 'Singapura' },
        { 'code': 'SY', 'name': 'Síria' },
        { 'code': 'SO', 'name': 'Somália' },
        { 'code': 'LK', 'name': 'Sri Lanka' },
        { 'code': 'SZ', 'name': 'Suazilândia' },
        { 'code': 'SD', 'name': 'Sudão' },
        { 'code': 'SS', 'name': 'Sudão do Sul' },
        { 'code': 'SE', 'name': 'Suécia' },
        { 'code': 'CH', 'name': 'Suíça' },
        { 'code': 'SR', 'name': 'Suriname' },
        { 'code': 'SJ', 'name': 'Svalbard e Jan Mayen' },
        { 'code': 'TH', 'name': 'Tailândia' },
        { 'code': 'TW', 'name': 'Taiwan' },
        { 'code': 'TJ', 'name': 'Tajiquistão' },
        { 'code': 'TZ', 'name': 'Tanzânia' },
        { 'code': 'TF', 'name': 'Terras Austrais e Antárticas Francesas' },
        { 'code': 'IO', 'name': 'Território Britânico do Oceano Índico' },
        { 'code': 'TL', 'name': 'Timor-Leste' },
        { 'code': 'TG', 'name': 'Togo' },
        { 'code': 'TK', 'name': 'Toquelau' },
        { 'code': 'TO', 'name': 'Tonga' },
        { 'code': 'TT', 'name': 'Trinidad e Tobago' },
        { 'code': 'TN', 'name': 'Tunísia' },
        { 'code': 'TC', 'name': 'Turks e Caicos' },
        { 'code': 'TM', 'name': 'Turquemenistão' },
        { 'code': 'TR', 'name': 'Turquia' },
        { 'code': 'TV', 'name': 'Tuvalu' },
        { 'code': 'UA', 'name': 'Ucrânia' },
        { 'code': 'UG', 'name': 'Uganda' },
        { 'code': 'UY', 'name': 'Uruguai' },
        { 'code': 'UZ', 'name': 'Uzbequistão' },
        { 'code': 'VU', 'name': 'Vanuatu' },
        { 'code': 'VA', 'name': 'Vaticano' },
        { 'code': 'VE', 'name': 'Venezuela' },
        { 'code': 'VN', 'name': 'Vietnã' },
        { 'code': 'VI', 'name': 'Ilhas Virgens Americanas' },
        { 'code': 'VG', 'name': 'Ilhas Virgens Britânicas' },
        { 'code': 'WF', 'name': 'Wallis e Futuna' },
        { 'code': 'ZM', 'name': 'Zâmbia' },
        { 'code': 'ZW', 'name': 'Zimbabwe' },
    ];
    result['eevc_request'] = [
        { 'code': '0017', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '0021', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '0041', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '0042', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '0050', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '0097', 'name': 'Solicitação do comprovante entrega mercadoria', 'documents': 'Cópia do comprovante de entrega da mercadoria legível e cópia da consulta realizada por meio do avs com o código w.' },
        { 'code': '3001', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '5001', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '3002', 'name': '2a solicitaçãode comprovante/documentos legíveis', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '5060', 'name': '2a solicitaçãode comprovante/documentos legíveis', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '3003', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '5003', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '3040', 'name': 'Desmembramento de transações', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão, RG do portador;- Carta explicativa que deverá conter os esclarecimentos: motivo da realização.' },
        { 'code': '3053', 'name': 'Mercadoria com defeito', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '5053', 'name': 'Mercadoria com defeito', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '3055', 'name': 'Não recebimento de mercadoria', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador; - Nota fiscal; - Documentação que comprove a entrega da mercadoria; - Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '5030', 'name': 'Não recebimento de mercadoria', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador; - Nota fiscal; - Documentação que comprove a entrega da mercadoria; - Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '3059', 'name': 'Serviços não prestados', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador; - Nota fiscal; - Documentação que comprove a prestação do serviço; - Carta explicativa com objetivo de esclarecer ocorrido.' },
        { 'code': '5130', 'name': 'Serviços não prestados', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador; - Nota fiscal; - Documentação que comprove a prestação do serviço; - Carta explicativa com objetivo de esclarecer ocorrido.' },
        { 'code': '3060', 'name': 'Cancelamento de transação', 'documents': 'Carta explicativa com objetivo de esclarecer o ocorrido. Esta carta terá o detalhamento de todo o ocorrido, informando a veracidade da contestação.' },
        { 'code': '5085', 'name': 'Cancelamento de transação', 'documents': 'Carta explicativa com objetivo de esclarecer o ocorrido. Esta carta terá o detalhamento de todo o ocorrido, informando a veracidade da contestação.' },
        { 'code': '3097', 'name': 'Solicitação do comprovante entrega mercadoria', 'documents': 'Cópia do comprovante de entrega da mercadoria legível e cópia da consulta realizada por meio do avs com o código w.' },
        { 'code': '5097', 'name': 'Solicitação do comprovante entrega mercadoria', 'documents': 'Cópia do comprovante de entrega da mercadoria legível e cópia da consulta realizada por meio do avs com o código w.' },
        { 'code': '3140', 'name': 'Desmembramento de transações', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador;' },
        { 'code': '3153', 'name': 'Mercadoria/serviço não confere com descrição', 'documents': 'Carta explicativa que deverá conter os esclarecimentos: motivo da realização de várias transações no mesmo estabelecimento e explicação do que compõe os valores acima;- Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador;- Nota fiscal;- Documentação que comprove a entrega da mercadoria/serviço exatamente como foi solicitado pelo portador do cartão;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '5153', 'name': 'Mercadoria/serviço não confere com descrição', 'documents': 'Carta explicativa que deverá conter os esclarecimentos: motivo da realização de várias transações no mesmo estabelecimento e explicação do que compõe os valores acima;- Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador;- Nota fiscal;- Documentação que comprove a entrega da mercadoria/serviço exatamente como foi solicitado pelo portador do cartão;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '3159', 'name': 'Pagamento por outros meios', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador;- Nota fiscal;- Documentação que comprove o pagamento efetuado por outros meios;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '5086', 'name': 'Pagamento por outros meios', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador;- Nota fiscal;- Documentação que comprove o pagamento efetuado por outros meios;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '3160', 'name': 'Cancelamento e/oudevolução total/parcial mercadoria', 'documents': 'Carta explicativa com objetivo de esclarecer o ocorrido. Esta carta terá o detalhamento de todo o ocorrido, informando a veracidade da contestação;- Documentação que comprove a devolução total e/ou parcial da mercadoria;- Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão;- RG do portador;- Nota fiscal;' },
        { 'code': '5185', 'name': 'Cancelamento e/oudevolução total/parcial mercadoria', 'documents': 'Carta explicativa com objetivo de esclarecer o ocorrido. Esta carta terá o detalhamento de todo o ocorrido, informando a veracidade da contestação;- Documentação que comprove a devolução total e/ou parcial da mercadoria;- Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão;- RG do portador;- Nota fiscal;' },
        { 'code': '3253', 'name': 'Mercadoria devolvida', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão;- RG do portador;- Nota fiscal;- Documentação que comprove a devolução da mercadoria;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '5253', 'name': 'Mercadoria devolvida', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão;- RG do portador;- Nota fiscal;- Documentação que comprove a devolução da mercadoria;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '3259', 'name': 'Contestação de adendo de transação', 'documents': 'Carta explicativa que deverá conter os esclarecimentos abaixo e a documentação comprobatória, além das cópias legíveis do comprovante de vendas e da respectiva nota fiscal: 1) A venda contestada é de transação adicional referente a uma transação realizada anteriormente neste estabelecimento? (a transação anterior pode ter sido paga em dinheiro, cartão ou outro meio de pagamento). 2) A cobrança adicional foi autorizada pelo portador do cartão? (enviar documento que comprove a autorização do portador).' },
        { 'code': '5230', 'name': 'Contestação de adendo de transação', 'documents': 'Carta explicativa que deverá conter os esclarecimentos abaixo e a documentação comprobatória, além das cópias legíveis do comprovante de vendas e da respectiva nota fiscal: 1) A venda contestada é de transação adicional referente a uma transação realizada anteriormente neste estabelecimento? (a transação anterior pode ter sido paga em dinheiro, cartão ou outro meio de pagamento). 2) A cobrança adicional foi autorizada pelo portador do cartão? (enviar documento que comprove a autorização do portador).' },
        { 'code': '6300', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7000', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6305', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7028', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6321', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7029', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6322', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7030', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6323', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7033', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6341', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '7034', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6342', 'name': 'Solicitação do comprovante/documentos', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão e RG do portador.' },
        { 'code': '6355', 'name': 'Não recebimento de mercadoria', 'documents': 'Comprovante de vendas com os dados legíveis e se a venda foi realizada com autorização de débito (assinatura em arquivo), além deste documento, envie também cópias do cartão; RG do portador;- Nota fiscal;- Documentação que comprove a entrega da mercadoria;- Carta explicativa com objetivo de esclarecer o ocorrido.' },
        { 'code': '6397', 'name': 'Solicitação do comprovante entrega mercadoria', 'documents': 'Cópia do comprovante de entrega da mercadoria legível e cópia da consulta realizada por meio do avs com o código w.' },
        { 'code': '7097', 'name': 'Solicitação do comprovante entrega mercadoria', 'documents': 'Cópia do comprovante de entrega da mercadoria legível e cópia da consulta realizada por meio do avs com o código w.' },
        { 'code': '5082', 'name': 'Rq. dupl. multiplos adquirentes', 'documents': 'Caso o portador tenha realizado realmente as duas transações, envie para a rede as cópias legíveis dos dois comprovantes de vendas.' },
        { 'code': '3034', 'name': 'Rq. dupl. multiplos adquirentes', 'documents': 'Para contestação por duplicidade da transação: cópia de ambos os comprovantes das vendas evidenciando as transações distintas. Para contestação por pagamento efetuado por outros meios, por erro no processamento do valor ou na quantidade de parcelas da transação, ou por não fornecimento do código de moeda correto: cópia do comprovante da transação que comprove a legitimidade da transação e carta explicativa detalhando o ocorrido.' },    
    ];
    result['eevd_status'] = [
        { 'code': '01', 'name': 'Acatada' },
    ];
    result['eevd_tipo_resumo'] = [
        { 'code': 'D', 'name': 'Débito à vista' },
        { 'code': 'P', 'name': 'Pré-datado' },
    ];
    result['eevd_tipo_captura'] = [
        { 'code': '1', 'name': 'Manual' },
        { 'code': '2', 'name': 'POS' },
        { 'code': '3', 'name': 'PDV' },
        { 'code': '4', 'name': 'TO' },
        { 'code': '5', 'name': 'Internet' },
        { 'code': '6', 'name': 'Leitor de trilha' },
        { 'code': '9', 'name': 'Outros' }
    ];
    result['eevd_tipo_transacao'] = [
        { 'code': 'V', 'name': 'Cartão de débito à vista' },
        { 'code': 'C', 'name': 'CDC' },
        { 'code': 'T', 'name': 'Trishop' },
        { 'code': 'S', 'name': 'Construcard' },
        { 'code': 'P', 'name': 'Pré-datado' },
        { 'code': 'F', 'name': 'Pagamento de fatura' }
    ];
    result['eevd_bandeiras'] = [
        { 'code': '0', 'name': 'Outras bandeiras' },
        { 'code': '1', 'name': 'Maestro' },
        { 'code': '3', 'name': 'Visa Electron' },
        { 'code': '4', 'name': 'Cabal' },
        { 'code': '9', 'name': 'Sicredi' },
        { 'code': 'H', 'name': 'Hiper' },
        { 'code': 'A', 'name': 'Avista' },
        { 'code': 'B', 'name': 'Banescard' },
        { 'code': 'E', 'name': 'Elo' },
        { 'code': 'X', 'name': 'Amex' },
    ];
    result['eevd_tipo_movimento'] = [
        { 'code': 'D', 'name': 'Desagendamento' },
        { 'code': 'N', 'name': 'Net' }
    ];
    result['eevd_tipo_ajuste'] = [
        { 'code': 'D', 'name': 'Débito' },
        { 'code': 'C', 'name': 'Crédito' }
    ];
    result['eefi_tipo_status'] = [
        { 'code': '00', 'name': 'CV OK' },
        { 'code': '01', 'name': 'A emitir' },
        { 'code': '02', 'name': 'Trânsito' },
        { 'code': '03', 'name': 'Pendente banco' },
        { 'code': '04', 'name': 'Pendente matriz' },
        { 'code': '05', 'name': 'Pendente filial' },
        { 'code': '06', 'name': 'Baixada' },
        { 'code': '07', 'name': 'Trânsito em fita' },
        { 'code': '08', 'name': 'Baixa automática' },
        { 'code': '09', 'name': 'Baixado para penhora ou retenção' },
        { 'code': '11', 'name': 'Suspenso' },
        { 'code': '12', 'name': 'Penhorado' },
        { 'code': '13', 'name': 'Retido' },
    ];
    result['eefi_bandeiras'] = [
        { 'code': '0', 'name': 'Other Flags' },
        { 'code': '1', 'name': 'MasterCard' },
        { 'code': '2', 'name': 'Diners Club' },
        { 'code': '3', 'name': 'Visa' },
        { 'code': '4', 'name': 'Cabal' },
        { 'code': '5', 'name': 'Hipercard' },
        { 'code': '6', 'name': 'Sorocred' },
        { 'code': '7', 'name': 'CUP' },
        { 'code': '8', 'name': 'Credsystem (Mais)' },
        { 'code': '9', 'name': 'Sicredi' },
        { 'code': 'A', 'name': 'Avista' },
        { 'code': 'B', 'name': 'Banescard' },
        { 'code': 'J', 'name': 'JCB' },
        { 'code': 'Z', 'name': 'Credz' },
        { 'code': 'E', 'name': 'Elo' },
        { 'code': 'X', 'name': 'Amex' },
    ];
    result['eefi_tipo_movimento'] = [
        { 'code': 'D', 'name': 'Desagendamento' },
        { 'code': 'N', 'name': 'Net' }
    ];
    result['eefi_tipo_ajuste'] = [
        { 'code': 'D', 'name': 'Débito' },
        { 'code': 'C', 'name': 'Crédito' }
    ];
    result['eesa_tipo_ajuste'] = [
        { 'code': 'D', 'name': 'Débito' },
        { 'code': 'C', 'name': 'Crédito' }
    ];
    result['eesa_bandeiras'] = [
        { 'code': '0', 'name': 'Other Flags' },
        { 'code': '1', 'name': 'MasterCard' },
        { 'code': '2', 'name': 'Diners Club' },
        { 'code': '3', 'name': 'Visa' },
        { 'code': '4', 'name': 'Cabal' },
        { 'code': '5', 'name': 'Hipercard' },
        { 'code': '6', 'name': 'Sorocred' },
        { 'code': '7', 'name': 'CUP' },
        { 'code': '8', 'name': 'Credsystem (Mais)' },
        { 'code': '9', 'name': 'Sicredi' },
        { 'code': 'A', 'name': 'Avista' },
        { 'code': 'B', 'name': 'Banescard' },
        { 'code': 'E', 'name': 'Elo' },
        { 'code': 'J', 'name': 'JCB' },
        { 'code': 'X', 'name': 'Amex' },
        { 'code': 'Z', 'name': 'Credz' },
    ];
    result['eesa_status_credito'] = [
        { 'code': '00', 'name': 'CV OK' },
        { 'code': '01', 'name': 'A emitir' },
        { 'code': '02', 'name': 'Trânsito' },
        { 'code': '03', 'name': 'Pendente banco' },
        { 'code': '04', 'name': 'Pendente matriz' },
        { 'code': '05', 'name': 'Pendente filial' },
        { 'code': '06', 'name': 'Baixada' },
        { 'code': '07', 'name': 'Trânsito em fita' },
        { 'code': '08', 'name': 'Baixa automática' },
        { 'code': '09', 'name': 'Baixado para penhora ou retenção' },
        { 'code': '11', 'name': 'Suspenso' },
        { 'code': '12', 'name': 'Penhorado' },
        { 'code': '13', 'name': 'Retido' },
    ];
    return result;  
}

export const getIdTable = (fileType, property, value) => {
    const Tables = getTables();
    let key = fileType + '_' + property;
    let findValue = _.find(Tables[key], { 'code': value });

    if (!findValue) {
        findValue = { 'code': value, 'name': value, 'documents': '' };
    }

    return findValue;
}