import _ from 'lodash'


const getTables = () => {
    const result = {};

    result['tipo_conta'] = [
        { 'code': '', 'name': 'CONTA DE LIVRE MOVIMENTO' },
        { 'code': '0200', 'name': 'CONTA INVESTIMENTO' },
        { 'code': '0201', 'name': 'APLIC AUT' },
        { 'code': '0202', 'name': 'APLICAUT MAIS' },
    ];

    result['natureza_lancamento'] = [
        { 'code': 'CDS', 'name': 'LANÇAMENTO COMPOSTO DE RECURSOS DISPONÍVEIS E BLOQUEADOS' },
        { 'code': 'DPV', 'name': 'LANÇAMENTO OCORRIDO EM RECURSO DISPONÍVEL' },
        { 'code': 'SCR', 'name': 'LANÇAMENTO OCORRIDO EM RECURSO DISPONÍVEL, PORÉM NÃO LIBERADO PARA USO' },
        { 'code': 'SSR', 'name': 'LANÇAMENTO OCORRIDO EM RECURSO A COMPENSAR' },
    ];

    result['isento_cpmf'] = [
        { 'code': 'S', 'name': 'ISENTO' },
        { 'code': 'N', 'name': 'NÃO ISENTO' },
        { 'code': 'B', 'name': 'BONIFICADO' },
    ];

    result['ident_lancamento'] = [
        { 'code': '1', 'name': 'LANÇAMENTO NORMAL EM RECURSO DISPONÍVEL' },
        { 'code': '2', 'name': 'LANÇAMENTO NORMAL EM RECURSO A COMPENSAR' },
        { 'code': '5', 'name': 'LANÇAMENTOS FUTUROS' },
    ];

    result['categoria_lancamento'] = [
        { 'code': '101', 'name': 'CHEQUES' },
        { 'code': '102', 'name': 'ENCARGOS' },
        { 'code': '103', 'name': 'ESTORNOS' },
        { 'code': '104', 'name': 'LANÇAMENTOS AVISADOS' },
        { 'code': '105', 'name': 'TARIFAS' },
        { 'code': '106', 'name': 'APLICAÇÃO' },
        { 'code': '107', 'name': 'EMPRESTIMO / FINANCIAMENTO' },
        { 'code': '108', 'name': 'CAMBIO' },
        { 'code': '109', 'name': 'CPMF' },
        { 'code': '110', 'name': 'IOF' },
        { 'code': '111', 'name': 'IMPOSTO DE RENDA' },
        { 'code': '112', 'name': 'PAGAMENTO FORNECEDORES' },
        { 'code': '113', 'name': 'PAGAMENTO FUNCIONÁRIOS' },
        { 'code': '114', 'name': 'SAQUE ELETRÔNICO' },
        { 'code': '115', 'name': 'AÇÕES' },
        { 'code': '116', 'name': 'SEGURO' },
        { 'code': '117', 'name': 'TRANSFERÊNCIA ENTRE CONTAS' },
        { 'code': '118', 'name': 'DEVOLUÇÃO DA COMPENSAÇÃO' },
        { 'code': '119', 'name': 'DEVOLUÇÃO DE CHEQUES' },
        { 'code': '120', 'name': 'TRANSF. INTERBANCÁRIAS (DOC/TED)' },
        { 'code': '121', 'name': 'DESCONTO DE DUPLICATAS' },
        { 'code': '201', 'name': 'DEPÓSITOS' },
        { 'code': '202', 'name': 'COBRANÇA' },
        { 'code': '203', 'name': 'DEVOLUÇÃO DE CHEQUES' },
        { 'code': '204', 'name': 'ESTORNOS' },
        { 'code': '205', 'name': 'LANÇAMENTOS AVISADOS' },
        { 'code': '206', 'name': 'RESGATE DE APLICAÇÕES' },
        { 'code': '207', 'name': 'EMPRÉSTIMO / FINANCIAMENTO' },
        { 'code': '208', 'name': 'CAMBIO' },
        { 'code': '209', 'name': 'TRANSF. INTERBANCÁRIAS (DOC/TED)' },
        { 'code': '210', 'name': 'AÇÕES' },
        { 'code': '211', 'name': 'DIVIDENDOS' },
        { 'code': '212', 'name': 'SEGURO' },
        { 'code': '213', 'name': 'TRANSFERÊNCIA ENTRE CONTAS' },
        { 'code': '214', 'name': 'DEPÓSITOS ESPECIAIS' },
        { 'code': '215', 'name': 'DEVOLUÇÃO DE COMPENSAÇÃO' },
    ];

    result['cod_fluxo_caixa'] = [
        { 'code': '0000', 'name': 'OUTROS LANÇAMENTOS', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0001', 'name': 'CHEQUE PAGO NO CAIXA', 'debit': '101', 'credit': '205', 'swift': 'CHK' },
        { 'code': '0002', 'name': 'RECIBO RET CH AVULSO', 'debit': '101', 'credit': '205', 'swift': 'CHK' },
        { 'code': '0003', 'name': 'COMPENSACAO RECEBIDA', 'debit': '101', 'credit': '205', 'swift': 'CHK' },
        { 'code': '0004', 'name': 'COMP INTERNA RECEBIDA', 'debit': '101', 'credit': '205', 'swift': 'CHK' },
        { 'code': '0005', 'name': 'CHEQUE OP', 'debit': '101', 'credit': '205', 'swift': 'CLR' },
        { 'code': '0006', 'name': 'CHEQUE VISADO', 'debit': '101', 'credit': '205', 'swift': 'CHK' },
        { 'code': '0007', 'name': 'TEDs RECEBIDAS', 'debit': '104', 'credit': '209', 'swift': 'DCR' },
        { 'code': '0008', 'name': 'TEDs ENVIADAS', 'debit': '120', 'credit': '205', 'swift': 'DCR' },
        { 'code': '0011', 'name': 'DOCs DEPOSITADOS', 'debit': '104', 'credit': '209', 'swift': 'DCR' },
        { 'code': '0012', 'name': 'EMISSAO DE DOCs', 'debit': '120', 'credit': '205', 'swift': 'DCR' },
        { 'code': '0015', 'name': 'DEPOSITO DINHEIRO', 'debit': '104', 'credit': '201', 'swift': 'MSC' },
        { 'code': '0016', 'name': 'DEP.DINHEIRO C/ CARTAO', 'debit': '104', 'credit': '201', 'swift': 'MSC' },
        { 'code': '0017', 'name': 'DEPOSITO EM CHEQUES', 'debit': '104', 'credit': '201', 'swift': 'MSC' },
        { 'code': '0018', 'name': 'DEP.CHEQUE-AUTO-ATEND', 'debit': '104', 'credit': '201', 'swift': 'MSC' },
        { 'code': '0019', 'name': 'DEP.CHEQUE C/ CARTAO', 'debit': '104', 'credit': '201', 'swift': 'MSC' },
        { 'code': '0025', 'name': 'CREI', 'debit': '104', 'credit': '214', 'swift': 'COL' },
        { 'code': '0026', 'name': 'SISREC', 'debit': '104', 'credit': '214', 'swift': 'COL' },
        { 'code': '0027', 'name': 'DEPOSITO IDENTIFICADO', 'debit': '104', 'credit': '214', 'swift': 'COL' },
        { 'code': '0028', 'name': 'COPEI', 'debit': '104', 'credit': '214', 'swift': 'COL' },
        { 'code': '0029', 'name': 'OUTROS DEPOSITOS ESPEC', 'debit': '104', 'credit': '214', 'swift': 'MSC' },
        { 'code': '0032', 'name': 'DEVOL CH. - EXPEDIDA', 'debit': '104', 'credit': '203', 'swift': 'RTI' },
        { 'code': '0033', 'name': 'DEVOL CH. - RECEBIDA', 'debit': '119', 'credit': '205', 'swift': 'RTI' },
        { 'code': '0034', 'name': 'DEVOL DOC - EXPED.', 'debit': '118', 'credit': '205', 'swift': 'RTI' },
        { 'code': '0035', 'name': 'DEVOL DOC - RECEB.', 'debit': '104', 'credit': '215', 'swift': 'RTI' },
        { 'code': '0038', 'name': 'COBRANCA RECEBIDA', 'debit': '104', 'credit': '202', 'swift': 'COL' },
        { 'code': '0039', 'name': 'COBRANCA EXPEDIDA', 'debit': '104', 'credit': '202', 'swift': 'COL' },
        { 'code': '0041', 'name': 'OPERACAO CRED./FINANC.', 'debit': '107', 'credit': '207', 'swift': 'LDP' },
        { 'code': '0042', 'name': 'DESCONTO DUPL./CHEQUE', 'debit': '107', 'credit': '207', 'swift': 'LDP' },
        { 'code': '0045', 'name': 'APLICACOES', 'debit': '106', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0046', 'name': 'DEVOLUÇÃO TED - RECEBIDA', 'debit': '104', 'credit': '215', 'swift': 'RTI' },
        { 'code': '0047', 'name': 'DEVOLUÇÃO TED - EXPEDIDA', 'debit': '118', 'credit': '205', 'swift': 'RTI' },
        { 'code': '0048', 'name': 'RESGATE DE APLICACOES', 'debit': '104', 'credit': '206', 'swift': 'MSC' },
        { 'code': '0051', 'name': 'CAMBIO', 'debit': '108', 'credit': '208', 'swift': 'FEX' },
        { 'code': '0054', 'name': 'ACOES', 'debit': '115', 'credit': '210', 'swift': 'BRF' },
        { 'code': '0057', 'name': 'DIVIDENDOS', 'debit': '104', 'credit': '211', 'swift': 'DIV' },
        { 'code': '0060', 'name': 'SEGUROS', 'debit': '116', 'credit': '212', 'swift': 'SEC' },
        { 'code': '0063', 'name': 'TRANSF. ENTRE CONTAS', 'debit': '117', 'credit': '213', 'swift': 'TRF' },
        { 'code': '0066', 'name': 'SAQUES ELETRONICOS', 'debit': '114', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0069', 'name': 'PAGTOS FORNECEDOR', 'debit': '112', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0070', 'name': 'PAGTOS FUNCIONARIO', 'debit': '113', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0071', 'name': 'PAGTOS DIVERSOS', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0074', 'name': 'TARIFAS', 'debit': '105', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0075', 'name': 'TAXAS', 'debit': '105', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0077', 'name': 'ENCARGOS', 'debit': '102', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0080', 'name': 'CPMF', 'debit': '109', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0081', 'name': 'ESTORNO CPMF', 'debit': '109', 'credit': '204', 'swift': 'CHG' },
        { 'code': '0082', 'name': 'BONUS CPMF', 'debit': '109', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0083', 'name': 'IOF', 'debit': '110', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0084', 'name': 'OUTROS CPMF', 'debit': '109', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0086', 'name': 'IR', 'debit': '111', 'credit': '205', 'swift': 'CHG' },
        { 'code': '0089', 'name': 'ESTORNO', 'debit': '103', 'credit': '204', 'swift': 'RTI' },
        { 'code': '0092', 'name': 'CARTÃO PERSONALITÊ', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0093', 'name': 'CARTÃO DE CRÉDITO', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0096', 'name': 'RESSARCIMENTO DE VALORES', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0098', 'name': 'RECEBIMENTO DIVERSOS', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
        { 'code': '0099', 'name': 'COLETA DE VALORES', 'debit': '104', 'credit': '205', 'swift': 'MSC' },
    ];

    result['tipo_inscricao'] = [
        { 'code': '01', 'name': 'CPF DO BENEFICIÁRIO' },
        { 'code': '02', 'name': 'CNPJ DO BENEFICIÁRIO' },
        { 'code': '03', 'name': 'CPF DO SACADOR' },
        { 'code': '04', 'name': 'CNPJ DO SACADOR' },
    ];

    result['tipo_ocorrencia'] = [
        { 'code': '02', 'name': 'ENTRADA CONFIRMADA' } ,
        { 'code': '03', 'name': 'ENTRADA REJEITADA' } ,
        { 'code': '04', 'name': 'ALTERAÇÃO DE DADOS - NOVA ENTRADA OU ALTERAÇÃO/EXCLUSÃO DE DADOS ACATADA' } ,
        { 'code': '05', 'name': 'ALTERAÇÃO DE DADOS - BAIXA' } ,
        { 'code': '06', 'name': 'LIQUIDAÇÃO NORMAL' } ,
        { 'code': '07', 'name': 'LIQUIDAÇÃO PARCIAL - COBRANÇA INTELIGENTE (B2B)' } ,
        { 'code': '08', 'name': 'LIQUIDAÇÃO EM CARTÓRIO' } ,
        { 'code': '09', 'name': 'BAIXA SIMPLES' } ,
        { 'code': '10', 'name': 'BAIXA POR TER SIDO LIQUIDADO' } ,
        { 'code': '11', 'name': 'EM SER (SÓ NO RETORNO MENSAL)' } ,
        { 'code': '12', 'name': 'ABATIMENTO CONCEDIDO' } ,
        { 'code': '13', 'name': 'ABATIMENTO CANCELADO' } ,
        { 'code': '14', 'name': 'VENCIMENTO ALTERADO' } ,
        { 'code': '15', 'name': 'BAIXAS REJEITADAS' } ,
        { 'code': '16', 'name': 'INSTRUÇÕES REJEITADAS' } ,
        { 'code': '17', 'name': 'ALTERAÇÃO/EXCLUSÃO DE DADOS REJEITADOS' } ,
        { 'code': '18', 'name': 'COBRANÇA CONTRATUAL - INSTRUÇÕES/ALTERAÇÕES REJEITADAS/PENDENTES' } ,
        { 'code': '19', 'name': 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE PROTESTO' } ,
        { 'code': '20', 'name': 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE SUSTAÇÃO DE PROTESTO /TARIFA' } ,
        { 'code': '21', 'name': 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE NÃO PROTESTAR' } ,
        { 'code': '23', 'name': 'TÍTULO ENVIADO A CARTÓRIO/TARIFA' } ,
        { 'code': '24', 'name': 'INSTRUÇÃO DE PROTESTO REJEITADA / SUSTADA / PENDENTE' } ,
        { 'code': '25', 'name': 'ALEGAÇÕES DO PAGADOR' } ,
        { 'code': '26', 'name': 'TARIFA DE AVISO DE COBRANÇA' } ,
        { 'code': '27', 'name': 'TARIFA DE EXTRATO POSIÇÃO (B40X)' } ,
        { 'code': '28', 'name': 'TARIFA DE RELAÇÃO DAS LIQUIDAÇÕES' } ,
        { 'code': '29', 'name': 'TARIFA DE MANUTENÇÃO DE TÍTULOS VENCIDOS' } ,
        { 'code': '30', 'name': 'DÉBITO MENSAL DE TARIFAS (PARA ENTRADAS E BAIXAS)' } ,
        { 'code': '32', 'name': 'BAIXA POR TER SIDO PROTESTADO' } ,
        { 'code': '33', 'name': 'CUSTAS DE PROTESTO' } ,
        { 'code': '34', 'name': 'CUSTAS DE SUSTAÇÃO' } ,
        { 'code': '35', 'name': 'CUSTAS DE CARTÓRIO DISTRIBUIDOR' } ,
        { 'code': '36', 'name': 'CUSTAS DE EDITAL' } ,
        { 'code': '37', 'name': 'TARIFA DE EMISSÃO DE BOLETO/TARIFA DE ENVIO DE DUPLICATA' } ,
        { 'code': '38', 'name': 'TARIFA DE INSTRUÇÃO' } ,
        { 'code': '39', 'name': 'TARIFA DE OCORRÊNCIAS' } ,
        { 'code': '40', 'name': 'TARIFA MENSAL DE EMISSÃO DE BOLETO/TARIFA MENSAL DE ENVIO DE DUPLICATA' } ,
        { 'code': '41', 'name': 'DÉBITO MENSAL DE TARIFAS - EXTRATO DE POSIÇÃO (B4EP/B4OX)' } ,
        { 'code': '42', 'name': 'DÉBITO MENSAL DE TARIFAS - OUTRAS INSTRUÇÕES' } ,
        { 'code': '43', 'name': 'DÉBITO MENSAL DE TARIFAS - MANUTENÇÃO DE TÍTULOS VENCIDOS' } ,
        { 'code': '44', 'name': 'DÉBITO MENSAL DE TARIFAS - OUTRAS OCORRÊNCIAS' } ,
        { 'code': '45', 'name': 'DÉBITO MENSAL DE TARIFAS - PROTESTO' } ,
        { 'code': '46', 'name': 'DÉBITO MENSAL DE TARIFAS - SUSTAÇÃO DE PROTESTO' } ,
        { 'code': '47', 'name': 'BAIXA COM TRANSFERÊNCIA PARA DESCONTO' } ,
        { 'code': '48', 'name': 'CUSTAS DE SUSTAÇÃO JUDICIAL' } ,
        { 'code': '51', 'name': 'TARIFA MENSAL REF A ENTRADAS BANCOS CORRESPONDENTES NA CARTEIRA' } ,
        { 'code': '52', 'name': 'TARIFA MENSAL BAIXAS NA CARTEIRA' } ,
        { 'code': '53', 'name': 'TARIFA MENSAL BAIXAS EM BANCOS CORRESPONDENTES NA CARTEIRA' } ,
        { 'code': '54', 'name': 'TARIFA MENSAL DE LIQUIDAÇÕES NA CARTEIRA' } ,
        { 'code': '55', 'name': 'TARIFA MENSAL DE LIQUIDAÇÕES EM BANCOS CORRESPONDENTES NA CARTEIRA' } ,
        { 'code': '56', 'name': 'CUSTAS DE IRREGULARIDADE' } ,
        { 'code': '57', 'name': 'INSTRUÇÃO CANCELADA' } ,
        { 'code': '59', 'name': 'BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG' } ,
        { 'code': '60', 'name': 'ENTRADA REJEITADA CARNÊ' } ,
        { 'code': '61', 'name': 'TARIFA EMISSÃO AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)' } ,
        { 'code': '62', 'name': 'DÉBITO MENSAL DE TARIFA - AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)' } ,
        { 'code': '63', 'name': 'TÍTULO SUSTADO JUDICIALMENTE' } ,
        { 'code': '64', 'name': 'ENTRADA CONFIRMADA COM RATEIO DE CRÉDITO' } ,
        { 'code': '65', 'name': 'PAGAMENTO COM CHEQUE - AGUARDANDO COMPENSAÇÃO' } ,
        { 'code': '69', 'name': 'CHEQUE DEVOLVIDO' } ,
        { 'code': '71', 'name': 'ENTRADA REGISTRADA, AGUARDANDO AVALIAÇÃO' } ,
        { 'code': '72', 'name': 'BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG SEM TÍTULO CORRESPONDENTE' } ,
        { 'code': '73', 'name': 'CONFIRMAÇÃO DE ENTRADA NA COBRANÇA SIMPLES - ENTRADA NÃO ACEITA NA COBRANÇA CONTRATUAL' } ,
        { 'code': '74', 'name': 'INSTRUÇÃO DE NEGATIVAÇÃO EXPRESSA REJEITADA' } ,
        { 'code': '75', 'name': 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA' } ,
        { 'code': '76', 'name': 'CHEQUE COMPENSADO' } ,
        { 'code': '77', 'name': 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA' } ,
        { 'code': '78', 'name': 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA' } ,
        { 'code': '79', 'name': 'NEGATIVAÇÃO EXPRESSA INFORMACIONAL' } ,
        { 'code': '80', 'name': 'CONFIRMAÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA - TARIFA' } ,
        { 'code': '82', 'name': 'CONFIRMAÇÃO DO CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA - TARIFA' } ,
        { 'code': '83', 'name': 'CONFIRMAÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO - TARIFA' } ,
        { 'code': '85', 'name': 'TARIFA POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '86', 'name': 'TARIFA EMAIL COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '87', 'name': 'TARIFA SMS COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '88', 'name': 'TARIFA MENSAL POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '89', 'name': 'TARIFA MENSAL EMAIL COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '90', 'name': 'TARIFA MENSAL SMS COBRANÇA ATIVA ELETRÔNICA' } ,
        { 'code': '91', 'name': 'TARIFA MENSAL DE EXCLUSÃO DE ENTRADA DE NEGATIVAÇÃO EXPRESSA' } ,
        { 'code': '92', 'name': 'TARIFA MENSAL DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA' } ,
        { 'code': '93', 'name': 'TARIFA MENSAL DE EXCLUSÃO DE NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO' } ,
    ];

    result['especie_titulo'] = [
        { 'code': '01', 'name': 'DUPLICATA MERCANTIL' },
        { 'code': '02', 'name': 'NOTA PROMISSÓRIA' },
        { 'code': '03', 'name': 'NOTA DE SEGURO' },
        { 'code': '04', 'name': 'MENSALIDADE ESCOLAR' },
        { 'code': '05', 'name': 'RECIBO' },
        { 'code': '06', 'name': 'CONTRATO' },
        { 'code': '07', 'name': 'COSSEGUROS' },
        { 'code': '08', 'name': 'DUPLICATA DE SERVIÇO' },
        { 'code': '09', 'name': 'LETRA DE CÂMBIO' },
        { 'code': '13', 'name': 'NOTA DE DÉBITOS' },
        { 'code': '15', 'name': 'DOCUMENTO DE DÍVIDA' },
        { 'code': '16', 'name': 'ENCARGOS CONDOMINIAIS' },
        { 'code': '17', 'name': 'CONTA DE PRESTAÇÃO DE SERVIÇOS' },
        { 'code': '18', 'name': 'BOLETO DE PROPOSTA' },
        { 'code': '99', 'name': 'DIVERSOS' },
    ];

    result['tipo_dda'] = [
        { 'code': '0', 'name': 'NÃO É BOLETO DDA (PAGADOR NÃO ADERIU AO DDA ATÉ O MOMENTO)' },
        { 'code': '1', 'name': 'BOLETO DDA (PAGADOR ADERIU AO DDA EM AO MENOS UM BANCO DE RELACIONAMENTO)' },
    ];

    result['tipo_liquidacao'] = [
        { 'code': 'AA', 'name': 'CAIXA ELETRÔNICO ITAÚ', 'resource': 'DISPONÍVEL' },
        { 'code': 'AC', 'name': 'PAGAMENTO EM CARTÓRIO AUTOMATIZADO', 'resource': 'A COMPENSAR' },
        { 'code': 'AO', 'name': 'ACERTO ONLINE', 'resource': 'DISPONÍVEL' },
        { 'code': 'BC', 'name': 'BANCOS CORRESPONDENTES', 'resource': 'DISPONÍVEL' },
        { 'code': 'BF', 'name': 'ITAÚ BANKFONE', 'resource': 'DISPONÍVEL' },
        { 'code': 'BL', 'name': 'ITAÚ BANKLINE', 'resource': 'DISPONÍVEL' },
        { 'code': 'B0', 'name': 'OUTROS BANCOS - RECEBIMENTO OFF-LINE', 'resource': 'A COMPENSAR' },
        { 'code': 'B1', 'name': 'OUTROS BANCOS - PELO CÓDIGO DE BARRAS', 'resource': 'A COMPENSAR' },
        { 'code': 'B2', 'name': 'OUTROS BANCOS - PELA LINHA DIGITÁVEL', 'resource': 'A COMPENSAR' },
        { 'code': 'B3', 'name': 'OUTROS BANCOS - PELO AUTO ATENDIMENTO', 'resource': 'A COMPENSAR' },
        { 'code': 'B4', 'name': 'OUTROS BANCOS - RECEBIMENTO EM CASA LOTÉRICA', 'resource': 'A COMPENSAR' },
        { 'code': 'B5', 'name': 'OUTROS BANCOS - CORRESPONDENTE', 'resource': 'A COMPENSAR' },
        { 'code': 'B6', 'name': 'OUTROS BANCOS - TELEFONE', 'resource': 'A COMPENSAR' },
        { 'code': 'B7', 'name': 'OUTROS BANCOS - ARQUIVO ELETRÔNICO (Pagamento Efetuado por meio de troca de arquivos)', 'resource': 'A COMPENSAR' },
        { 'code': 'CC', 'name': 'AGÊNCIA ITAÚ - COM CHEQUE DE OUTRO BANCO ou (CHEQUE ITAÚ)*', 'resource': 'A COMPENSAR' },
        { 'code': 'CI', 'name': 'CORRESPONDENTE ITAÚ', 'resource': 'DISPONÍVEL' },
        { 'code': 'CK', 'name': 'SISPAG - SISTEMA DE CONTAS A PAGAR ITAÚ', 'resource': 'DISPONÍVEL' },
        { 'code': 'CP', 'name': 'AGÊNCIA ITAÚ - POR DÉBITO EM CONTA CORRENTE, CHEQUE ITAÚ* OU DINHEIRO', 'resource': 'DISPONÍVEL' },
        { 'code': 'DG', 'name': 'AGÊNCIA ITAÚ - CAPTURADO EM OFF-LINE', 'resource': 'DISPONÍVEL' },
        { 'code': 'LC', 'name': 'PAGAMENTO EM CARTÓRIO DE PROTESTO COM CHEQUE', 'resource': 'A COMPENSAR' },
        { 'code': 'EA', 'name': 'TERMINAL DE CAIXA', 'resource': 'DISPONÍVEL' },
        { 'code': 'Q0', 'name': 'AGENDAMENTO - PAGAMENTO AGENDADO VIA BANKLINE OU OUTRO CANAL ELETRÔNICO E LIQUIDADO NA DATA INDICADA', 'resource': 'DISPONÍVEL' },
        { 'code': 'RA', 'name': 'DIGITAÇÃO - REALIMENTAÇÃO AUTOMÁTICA', 'resource': 'DISPONÍVEL' },
        { 'code': 'ST', 'name': 'PAGAMENTO VIA SELTEC**', 'resource': 'DISPONÍVEL' },
    ];

    result['cod_instrucao'] = [
        { 'code': '000', 'name': 'Inclusão de débito' },
        { 'code': '999', 'name': 'Exclusão de débitos já agendados no Banco' },
    ];

    result['tipo_moeda'] = [
        { 'code': 'FAJ', 'name': 'FATOR ACUMULADO DE JUROS - TR (seguros)' },
        { 'code': 'IDT', 'name': 'IDTR-SEGUROS' },
        { 'code': 'REA', 'name': 'REAL' },
        { 'code': 'USD', 'name': 'DÓLAR AMERICANO' },
    ];

    result['tipo_mora'] = [
        { 'code': '00', 'name': 'Isento' },
        { 'code': '01', 'name': 'Juros Simples' },
        { 'code': '03', 'name': 'IDA (Importância por dia de atraso)' },
    ];

    result['ocorrencia_debito_240'] = [
        { 'code': '00', 'name': 'DÉBITO EFETUADO' },
        { 'code': '01', 'name': 'INSUFICIÊNCIA DE FUNDOS - DÉBITO NÃO EFETUADO' },
        { 'code': '02', 'name': 'DÉBITO CANCELADO' },
        { 'code': '03', 'name': 'DÉBITO AUTORIZADO PELA AGÊNCIA - EFETUADO' },
        { 'code': 'NA', 'name': 'DÉBITO NÃO AUTORIZADO' },
        { 'code': 'HA', 'name': 'LOTE NÃO ACEITO' },
        { 'code': 'HB', 'name': 'INSCRIÇÃO DA EMPRESA INVÁLIDA PARA O CONTRATO' },
        { 'code': 'HC', 'name': 'CONVÊNIO COM A EMPRESA INEXISTENTE/INVÁLIDO PARA O CONTRATO' },
        { 'code': 'AA', 'name': 'CONTROLE INVÁLIDO' },
        { 'code': 'AB', 'name': 'TIPO DE OPERAÇÃO INVÁLIDO' },
        { 'code': 'AC', 'name': 'TIPO DE SERVIÇO INVÁLIDO' },
        { 'code': 'AD', 'name': 'FORMA DE LANÇAMENTO INVÁLIDA' },
        { 'code': 'AF', 'name': 'CÓDIGO DE CONVÊNIO INVÁLIDO' },
        { 'code': 'AH', 'name': 'NR. SEQUENCIAL DO REGISTRO NO LOTE INVÁLIDO' },
        { 'code': 'AI', 'name': 'CÓDIGO DE SEGMENTO DE DETALHE INVÁLIDO' },
        { 'code': 'AJ', 'name': 'TIPO DE MOVIMENTO INVÁLIDO' },
        { 'code': 'AL', 'name': 'CÓDIGO DO BANCO INVÁLIDO' },
        { 'code': 'AM', 'name': 'AGÊNCIA MANTEDORA DA CONTA CORRENTE DO DEBIT ADO INVÁLIDA' },
        { 'code': 'AN', 'name': 'CONTA CORRENTE/DÍGITO VERIFICADORA DO DEBITADO INVÁLIDO' },
        { 'code': 'AP', 'name': 'DATA LANÇAMENTO INVÁLIDA' },
        { 'code': 'AQ', 'name': 'TIPO/QUANTIDADE DA MOEDA INVÁLIDA' },
        { 'code': 'AR', 'name': 'VALOR DO LANÇAMENTO INVÁLIDO' },
        { 'code': 'AS', 'name': 'PARCELA VINCULADA' },
        { 'code': 'BD', 'name': 'CONFIRMAÇÃO DE AGENDAMENTO' },
        { 'code': 'IA', 'name': 'TIPO DO ENCARGO INVÁLIDO' },
        { 'code': 'IB', 'name': 'C/C COM RESTRIÇÃO' },
        { 'code': 'IC', 'name': 'C/C DO DEBITADO EM LIQUIDAÇÃO' },
        { 'code': 'ID', 'name': 'VALOR DA MORA / TAXA DA MORA INVÁLIDA' },
        { 'code': 'IE', 'name': 'CONTA CORRENTE DO DEBITADO ENCERRADA' },
        { 'code': 'IF', 'name': 'TAXA DA MORA MAIOR QUE 50,00000 %' },
        { 'code': 'IG', 'name': 'COMPLEMENTO DE HISTÓRICO INVÁLIDO' },
        { 'code': 'IH', 'name': 'CONTA CORRENTE PARA CRÉDITO NÃO AUTORIZADA' },
        { 'code': 'II', 'name': 'CANCELAMENTO NÃO ENCONTRADO' },
        { 'code': 'IK', 'name': 'VALOR DO DÉBITO ACIMA DO LIMITE' },
        { 'code': 'IL', 'name': 'LIMITE DIÁRIO DE DÉBITO ULTRAPASSADO' },
        { 'code': 'IM', 'name': 'CPF/CNPJ DO DEBITADO INVÁLIDO' },
        { 'code': 'IN', 'name': 'CPF/CNPJ DO DEBITADO NÃO PERTENCE À CONTA CORRENTE INDICADA' },
        { 'code': 'IZ', 'name': 'RESERVADO ( DAT A DA MORA)' },
        { 'code': 'TA', 'name': 'LOTE NÃO ACEITO - TOTAIS DO LOTE COM DIFERENÇA' },
    ];

    result['ocorrencia_debito_150'] = [
        { 'code': '00', 'name': 'DÉBITO EFETUADO' },
        { 'code': '01', 'name': 'INSUFICIÊNCIA DE FUNDOS - DÉBITO NÃO EFETUADO' },
        { 'code': '02', 'name': 'CONTA CORRENTE NÃO CADASTRADA' },
        { 'code': '04', 'name': 'OUTRAS RESTRIÇÕES' },
        { 'code': '10', 'name': 'AGÊNCIA EM REGIME DE ENCERRAMENTO' },
        { 'code': '12', 'name': 'VALOR INVÁLIDO' },
        { 'code': '13', 'name': 'DATA DE LANÇAMENTO INVÁLIDA' },
        { 'code': '14', 'name': 'AGÊNCIA INVÁLIDA' },
        { 'code': '15', 'name': 'DAC DA CONTA CORRENTE INVÁLIDO' },
        { 'code': '18', 'name': 'DATA DO DÉBITO ANTERIOR À DO PROCESSAMENTO' },
        { 'code': '30', 'name': 'SEM CONTRATO DE DÉBITO AUTOMÁTICO' },
        { 'code': '31', 'name': 'DÉBITO EFETUADO EM DATA DIFERENTE DA DATA INFORMADA - FERIADO NA PRAÇA DE DÉBITO' },
        { 'code': '47', 'name': 'VALOR DO DÉBITO ACIMA DO LIMITE' },
        { 'code': '48', 'name': 'LIMITE DIÁRIO DE DÉBITOS ULTRAPASSADO' },
        { 'code': '49', 'name': 'CPF/CNPJ DO DEBITADO INVÁLIDO' },
        { 'code': '50', 'name': 'CPF/CNPJ DO DEBITADO NÃO PERTENCE À CONTA CORRENTE INDICADA' },
        { 'code': '96', 'name': 'MANUTENÇÃO DO CADASTRO' },
        { 'code': '97', 'name': 'CANCELAMENTO NÃO ENCONTRADO' },
        { 'code': '98', 'name': 'CANCELAMENTO NÃO EFETUADO - FORA DE TEMPO HÁBIL' },
        { 'code': '99', 'name': 'CANCELADO CONFORME SOLICITAÇÃO' },
        { 'code': 'NA', 'name': 'DÉBITO NÃO AUTORIZADO' },
        { 'code': 'AQ', 'name': 'TIPO/QUANTIDADE DE MOEDA INVÁLIDA' },
        { 'code': 'ID', 'name': 'VALOR DA MORA INVÁLIDO' },
        { 'code': 'BD', 'name': 'CONFIRMAÇÃO DE AGENDAMENTO' },
        { 'code': 'ID', 'name': 'IDENTIFICAÇÃO DO CLIENTE NÃO LOCALIZADA / INCONSISTENTE' },
        { 'code': 'IR', 'name': 'RESTRIÇÃO DE CADASTRAMENTO PELA EMPRESA' },
        { 'code': 'IC', 'name': 'CLIENTE CADASTRADO EM OUTRO BANCO COM DATA POSTERIOR' },
        { 'code': 'IN', 'name': 'CLIENTE NÃO CADASTRADO' },
        { 'code': 'IA', 'name': 'EXCLUSÃO SOLICITADA POR INTERESSE DO CLIENTE' },
        { 'code': 'IE', 'name': 'EXCLUSÃO POR ALTERAÇÃO CADASTRAL DO CLIENTE' },
        { 'code': 'IF', 'name': 'EXCLUSÃO POR TER SIDO TRANSFERIDO PARA OUTRO BANCO' },
        { 'code': 'IG', 'name': 'EXCLUSÃO POR INSUFICIÊNCIA DE FUNDOS' },
        { 'code': 'ID', 'name': 'IDENTIFICAÇÃO DO CLIENTE NÃO LOCALIZADA / INCONSISTENTE' },
        { 'code': 'IR', 'name': 'RESTRIÇÃO DE CADASTRAMENTO PELA EMPRESA' },
        { 'code': 'IN', 'name': 'CLIENTE NÃO CADASTRADO' },
    ];

    result['cod_movimento'] = [
        { 'code': '0', 'name': 'Inclusão de débito' },
        { 'code': '1', 'name': 'Exclusão de débitos agendados no Banco' },
    ];

    return result;
}

export const getIdTable = (property, value) => {
    const Tables = getTables();
    let findValue = _.find(Tables[property], { 'code': value });

    if (!findValue) {
        findValue = { 'code': value, 'name': value };
    }

    return findValue;
}
