import _ from 'lodash'

const getTables = () => {
    const result = {};

    result['van'] = [
      { 'code': 'I', 'name': 'OpenText' },
      { 'code': 'P', 'name': 'TIVIT' },
    ];
    result['opcao_extrato'] = [
      { 'code': '03', 'name': 'Vendas com Plano Parcelado' },
      { 'code': '04', 'name': 'Pagamentos' },
      { 'code': '06', 'name': 'Antecipação de Recebíveis' },
      { 'code': '07', 'name': 'Cessão de Recebíveis' },
      { 'code': '08', 'name': 'Parcelas Pendentes' },
      { 'code': '09', 'name': 'Saldo em Aberto' },
      { 'code': '10', 'name': 'Antecipação de Recebíveis Alelo' },
      { 'code': '12', 'name': 'Vendas Alelo' },
      { 'code': '13', 'name': 'Pagamentos Alelo' },
      { 'code': '14', 'name': 'Saldo em Aberto Alelo' },
      { 'code': '15', 'name': 'Negociação de Recebíveis' },
      { 'code': '16', 'name': 'Transações PIX' },
    ];
    result['tipo_transacao'] = [
      { 'code': '01', 'name': 'Venda' },
      { 'code': '02', 'name': 'Ajuste a Crédito' },
      { 'code': '03', 'name': 'Ajuste a Débito' },
      { 'code': '04', 'name': 'Plano Cielo' },
      { 'code': '05', 'name': 'Outros Lançamentos' },
    ];
    result['tipo_produto'] = [
      { 'code': '0', 'name': 'Crédito à Vista', 'kind': 'credito' },
      { 'code': '3', 'name': 'Parcelado Emissor', 'kind': 'credito' },
      { 'code': '4', 'name': 'Parcelado Loja', 'kind': 'credito' },
      { 'code': '5', 'name': 'Cartão de Débito', 'kind': 'debito' },
      { 'code': '6', 'name': 'Electron Pré-Datado', 'kind': 'debito' },
    ];
    result['ind_cartao_emitido'] = [
      { 'code': '0000', 'name': 'Serviço não atribuído' },
      { 'code': '0001', 'name': 'Cartão emitido no Brasil' },
      { 'code': '0002', 'name': 'Cartão emitido no exterior' },
    ];
    result['ind_taxa_entrada'] = [
      { 'code': '', 'name': 'Demais Tipos de Transação'},
      { 'code': 'TX', 'name': 'Taxa de embarque' },
      { 'code': 'VE', 'name': 'Valor da entrada' },
    ];
    result['motivo_rejeicao'] = [
      { 'code': '', 'name': 'Sem Rejeição' },
      { 'code': '002', 'name': 'Cartão inválido' },
      { 'code': '023', 'name': 'Outros erros' },
      { 'code': '031', 'name': 'Transação de saque com cartão Electron valor zerado' },
      { 'code': '039', 'name': 'Banco emissor inválido' },
      { 'code': '044', 'name': 'Data da transação inválida' },
      { 'code': '045', 'name': 'Código de autorização inválido' },
      { 'code': '055', 'name': 'Número de parcelas inválido' },
      { 'code': '056', 'name': 'Transação financiada para estabelecimento não autorizado' },
      { 'code': '057', 'name': 'Cartão em boletim protetor' },
      { 'code': '061', 'name': 'Número de cartão inválido' },
      { 'code': '066', 'name': 'Transação não autorizada' },
      { 'code': '067', 'name': 'Transação não autorizada' },
      { 'code': '069', 'name': 'Transação não autorizada' },
      { 'code': '070', 'name': 'Transação não autorizada' },
      { 'code': '071', 'name': 'Transação não autorizada' },
      { 'code': '072', 'name': 'Transação não autorizada' },
      { 'code': '073', 'name': 'Transação inválida' },
      { 'code': '074', 'name': 'Valor de transação inválido' },
      { 'code': '075', 'name': 'Número de cartão inválido' },
      { 'code': '077', 'name': 'Transação não autorizada' },
      { 'code': '078', 'name': 'Transação não autorizada' },
      { 'code': '079', 'name': 'Transação não autorizada' },
      { 'code': '080', 'name': 'Transação não autorizada' },
      { 'code': '081', 'name': 'Cartão vencido' },
      { 'code': '082', 'name': 'Transação não autorizada' },
      { 'code': '083', 'name': 'Transação não autorizada' },
      { 'code': '084', 'name': 'Transação não autorizada' },
      { 'code': '086', 'name': 'Transação não autorizada' },
      { 'code': '092', 'name': 'Banco emissor sem comunicação' },
      { 'code': '093', 'name': 'Desbalanceamento no plano parcelado' },
      { 'code': '094', 'name': 'Venda parcelada para cartão emitido no exterior' },
      { 'code': '097', 'name': 'Valor de parcela menor do que o permitido' },
      { 'code': '099', 'name': 'Banco emissor inválido' },
      { 'code': '100', 'name': 'Transação não autorizada' },
      { 'code': '101', 'name': 'Transação duplicada' },
      { 'code': '102', 'name': 'Transação duplicada' },
      { 'code': '124', 'name': 'BIN não cadastrado' },
      { 'code': '126', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '128', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '129', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '130', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '133', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '134', 'name': 'Transação de saque com cartão Electron inválida' },
      { 'code': '140', 'name': 'Estabelecimento não e-commerce' },
      { 'code': '141', 'name': 'Cartão travel - transação inválida' },
      { 'code': '143', 'name': 'Venda em dólar inválido' },
      { 'code': '145', 'name': 'Estabelecimento inválido para distribuição' },
      { 'code': '147', 'name': 'Parcelado emissor não habilitado' },
      { 'code': '150', 'name': 'Estabelecimento não financeiro' },
    ];
    result['status_pagamento'] = [
      { 'code': '00', 'name': 'Agendado' },
      { 'code': '01', 'name': 'Pago' },
      { 'code': '02', 'name': 'Enviado para o Banco' },
      { 'code': '03', 'name': 'A Confirmar' },
    ];
    result['cod_produto'] = [
      { 'code': '001', 'name': 'Agiplan crédito à vista', 'kind': 'credito' },
      { 'code': '002', 'name': 'Agiplan parcelado loja', 'kind': 'credito' },
      { 'code': '003', 'name': 'Banescard crédito à vista', 'kind': 'credito' },
      { 'code': '004', 'name': 'Banescard parcelado loja', 'kind': 'credito' },
      { 'code': '005', 'name': 'Esplanada crédito à vista', 'kind': 'credito' },
      { 'code': '006', 'name': 'Credz crédito à vista', 'kind': 'credito' },
      { 'code': '007', 'name': 'Esplanada parcelado loja', 'kind': 'credito' },
      { 'code': '008', 'name': 'Credz parcelado loja', 'kind': 'credito' },
      { 'code': '009', 'name': 'Elo Crediário', 'kind': 'credito' },
      { 'code': '010', 'name': 'Mastercard crédito à vista', 'kind': 'credito' },
      { 'code': '011', 'name': 'Maestro', 'kind': 'debito' },
      { 'code': '012', 'name': 'Mastercard parcelado loja', 'kind': 'credito' },
      { 'code': '013', 'name': 'Elo Construcard', 'kind': 'credito' },
      { 'code': '014', 'name': 'Elo Agro Débito', 'kind': 'debito' },
      { 'code': '015', 'name': 'Elo Agro Custeio', 'kind': 'credito' },
      { 'code': '016', 'name': 'Elo Agro Investimento', 'kind': 'credito' },
      { 'code': '017', 'name': 'Elo Agro Custeio + Débito', 'kind': 'credito' },
      { 'code': '018', 'name': 'Elo Agro Investimento + Débito', 'kind': 'credito' },
      { 'code': '019', 'name': 'Discover crédito à vista', 'kind': 'credito' },
      { 'code': '020', 'name': 'Diners crédito à vista', 'kind': 'credito' },
      { 'code': '021', 'name': 'Diners parcelado loja', 'kind': 'credito' },
      { 'code': '022', 'name': 'Agro Custeio + Débito', 'kind': 'credito' },
      { 'code': '023', 'name': 'Agro Investimento + Débito', 'kind': 'credito' },
      { 'code': '024', 'name': 'FCO Investimento', 'kind': 'credito' },
      { 'code': '025', 'name': 'Agro Electron', 'kind': 'debito' },
      { 'code': '026', 'name': 'Agro Custeio', 'kind': 'credito' },
      { 'code': '027', 'name': 'Agro Investimento', 'kind': 'credito' },
      { 'code': '028', 'name': 'Visa FCO Giro', 'kind': 'credito' },
      { 'code': '033', 'name': 'JCB', 'kind': 'credito' },
      { 'code': '036', 'name': 'Visa Saque com cartão de Débito', 'kind': 'debito' },
      { 'code': '037', 'name': 'Flex Car Visa Vale', 'kind': 'credito' },
      { 'code': '038', 'name': 'Credsystem crédito à vista', 'kind': 'credito' },
      { 'code': '039', 'name': 'Credsystem parcelado loja', 'kind': 'credito' },
      { 'code': '040', 'name': 'Visa Crédito à vista', 'kind': 'credito' },
      { 'code': '041', 'name': 'Visa Electron Débito à vista', 'kind': 'debito' },
      { 'code': '042', 'name': 'Visa Pedágio', 'kind': 'credito' },
      { 'code': '043', 'name': 'Visa Parcelado Loja', 'kind': 'credito' },
      { 'code': '044', 'name': 'Visa Electron Pré-Datado', 'kind': 'debito' },
      { 'code': '045', 'name': 'Alelo Refeição (Bandeira Visa/Elo)', 'kind': 'credito' },
      { 'code': '046', 'name': 'Alelo Alimentação (Bandeira Visa/Elo)', 'kind': 'credito' },
      { 'code': '058', 'name': 'Alelo Multibenefícios', 'kind': 'credito' },
      { 'code': '059', 'name': 'Alelo Auto', 'kind': 'credito' },
      { 'code': '061', 'name': 'Sorocred Crédito à vista', 'kind': 'credito' },
      { 'code': '062', 'name': 'Sorocred Parcelado Loja', 'kind': 'credito' },
      { 'code': '064', 'name': 'Visa Crediário', 'kind': 'credito' },
      { 'code': '065', 'name': 'Alelo Refeição (Bandeira Elo)', 'kind': 'credito' },
      { 'code': '066', 'name': 'Alelo Alimentação (Bandeira Elo)', 'kind': 'credito' },
      { 'code': '067', 'name': 'Visa Capital de Giro', 'kind': 'credito' },
      { 'code': '068', 'name': 'Visa Crédito Imobiliário', 'kind': 'credito' },
      { 'code': '069', 'name': 'Alelo Cultura', 'kind': 'credito' },
      { 'code': '070', 'name': 'Elo Crédito', 'kind': 'credito' },
      { 'code': '071', 'name': 'Elo Débito à vista', 'kind': 'debito' },
      { 'code': '072', 'name': 'Elo Parcelado loja', 'kind': 'credito' },
      { 'code': '079', 'name': 'Pagamento Carnê Visa Electron', 'kind': 'debito' },
      { 'code': '080', 'name': 'Visa Crédito Conversor de Moeda', 'kind': 'credito' },
      { 'code': '081', 'name': 'Mastercard Crédito Especializado (*)', 'kind': 'credito' },
      { 'code': '082', 'name': 'Amex crédito à vista', 'kind': 'credito' },
      { 'code': '083', 'name': 'Amex parcelado loja', 'kind': 'credito' },
      { 'code': '089', 'name': 'Elo Crédito Imobiliário', 'kind': 'credito' },
      { 'code': '091', 'name': 'Elo Crédito Especializado (*)', 'kind': 'credito' },
      { 'code': '094', 'name': 'Banescard Débito', 'kind': 'debito' },
      { 'code': '096', 'name': 'Cabal Crédito à vista', 'kind': 'credito' },
      { 'code': '097', 'name': 'Cabal Débito', 'kind': 'debito' },
      { 'code': '098', 'name': 'Cabal Parcelado Loja', 'kind': 'credito' },
      { 'code': '161', 'name': 'Hiper crédito à vista', 'kind': 'credito' },
      { 'code': '162', 'name': 'Hiper débito à vista', 'kind': 'debito' },
      { 'code': '163', 'name': 'Hiper parcelado loja', 'kind': 'credito' },
      { 'code': '164', 'name': 'Hipercard crédito à vista', 'kind': 'credito' },
      { 'code': '165', 'name': 'Hipercard parcelado loja', 'kind': 'credito' },
      { 'code': '342', 'name': 'Master Pedágio', 'kind': 'credito' },
      { 'code': '377', 'name': 'Elo Carnê', 'kind': 'credito' },
      { 'code': '378', 'name': 'Master Carnê', 'kind': 'credito' },
      { 'code': '380', 'name': 'Mastercard Crédito Conversor de Moeda', 'kind': 'credito' },
    ];
    result['origem_ajuste'] = [
      { 'code': '01', 'name': 'Acerto de correção monetária', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '02', 'name': 'Acerto de data de pagamento', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '03', 'name': 'Acerto de taxa de comissão', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '04', 'name': 'Acerto de valores não processados', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '05', 'name': 'Acerto de valores não recebidos', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '06', 'name': 'Acerto de valores não reconhecidos', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '07', 'name': 'Acerto de valores negociados', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '08', 'name': 'Acerto de valores processados indevidamente', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '09', 'name': 'Acerto de lançamento não compensado em conta-corrente', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '10', 'name': 'Acerto referente valores contestados', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '11', 'name': 'Acerto temporário de valores contestados', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '12', 'name': 'Acertos diversos', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '13', 'name': 'Acordo de cobrança', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '14', 'name': 'Acordo jurídico', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '15', 'name': 'Aplicação de multa Programa Monitoria Chargeback', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '16', 'name': 'Bloqueio de valor por ordem judicial', 'group': 'Bloqueio', 'kind': 'ajustes' },
      { 'code': '17', 'name': 'Cancelamento da venda', 'group': 'Cancelamento', 'kind': 'cancelamento' },
      { 'code': '18', 'name': 'Cobrança de tarifa operacional', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '19', 'name': 'Cobrança mensal Lynx Comércio', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '20', 'name': 'Cobrança Plano Cielo', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '21', 'name': 'Contrato de caução', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '22', 'name': 'Crédito de devolução do cancelamento banco emissor', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '23', 'name': 'Crédito EC referente contestação portador', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '24', 'name': 'Crédito por cancelamento rejeitado Cielo', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '25', 'name': 'Processamento do débito duplicado Visa Pedágio', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '26', 'name': 'Débito por venda realizada sem a leitura do chip', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '27', 'name': 'Débito por venda rejeitada no sistema Cielo', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '28', 'name': 'Débito referente à contestação do portador', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '29', 'name': 'Estorno de acordo jurídico', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '30', 'name': 'Estorno de contrato de caução', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '31', 'name': 'Estorno de acordo de cobrança', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '32', 'name': 'Estorno de bloqueio de valor por ordem judicial', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '33', 'name': 'Estorno de cancelamento de venda', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '34', 'name': 'Estorno de cobrança de tarifa operacional', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '35', 'name': 'Estorno de cobrança mensal Lynx Comércio', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '36', 'name': 'Estorno de cobrança Plano Cielo', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '37', 'name': 'Estorno de débito venda sem a leitura do Chip', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '38', 'name': 'Estorno de incentivo comercial', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '39', 'name': 'Estorno de Multa Programa Monitoria Chargeback', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '40', 'name': 'Estorno de rejeição ARV', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '41', 'name': 'Estorno de reversão de duplicidade do pagamento - ARV', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '42', 'name': 'Estorno de tarifa de cadastro', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '43', 'name': 'Estorno de extrato papel', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '44', 'name': 'Estorno de processamento duplicado de débito - Visa Pedágio', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '45', 'name': 'Incentivo comercial', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '46', 'name': 'Incentivo por venda de Recarga', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '47', 'name': 'Regularização de rejeição ARV', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '48', 'name': 'Reversão de duplicidade do pagamento - ARV', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '49', 'name': 'Tarifa de cadastro', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '50', 'name': 'Tarifa de extrato no papel', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '51', 'name': 'Aceleração de débito de antecipação', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '52', 'name': 'Débito por descumprimento de cláusula contratual', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '53', 'name': 'Débito por cancelamento de venda', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '54', 'name': 'Débito por não reconhecimento de compra', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '55', 'name': 'Débito por venda com cartão com validade vencida', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '56', 'name': 'Débito por não reconhecimento de compra', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '57', 'name': 'Débito por cancelamento e/ou devolução dos serviços', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '58', 'name': 'Débito por transação irregular', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '59', 'name': 'Débito por não entrega da mercadoria', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '60', 'name': 'Débito por serviços não prestados', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '61', 'name': 'Débito efetuado venda sem código de autorização', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '62', 'name': 'Débito efetuado venda com número cartão inválido', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '63', 'name': 'Débito por cópia de CV e/ou documento não atendido', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '64', 'name': 'Débito venda efetuada com autorização negada', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '65', 'name': 'Débito envio de CV e/ou documento ilegível', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '66', 'name': 'Débito por venda efetuada sem leitura de chip', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '67', 'name': 'Débito por venda em outra moeda', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '68', 'name': 'Débito venda processada incorretamente', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '69', 'name': 'Débito por cancelamento de venda', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '70', 'name': 'Débito por crédito em duplicidade', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '71', 'name': 'Débito por documentos solicitados e não recebidos', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '72', 'name': 'Débito envio de CV e/ou documento incorreto', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '73', 'name': 'Débito por envio de CV e/ou documento fora do prazo', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '74', 'name': 'Débito por não reconhecimento de despesa', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '75', 'name': 'Débito documentação solicitada incompleta', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '76', 'name': 'Débito estabelecimento não possui CV e/ou Doc.', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '77', 'name': 'Programa de monitoria de chargeback', 'group': 'Chargeback', 'kind': 'chargeback' },
      { 'code': '78', 'name': 'Serviços Score', 'group': 'Cobrança', 'kind': 'aluguel_equipamentos' },
      { 'code': '79', 'name': 'Reagendamento do débito de antecipação', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '80', 'name': 'Ajuste do débito de cessão', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '81', 'name': 'Cielo e-Commerce', 'kind': 'Acerto/Cobrança', 'kind': 'ajustes' },
      { 'code': '85', 'name': 'Cielo Controle (Excedente)', 'group': 'Acerto/Cobrança', 'kind': 'ajustes' },
      { 'code': '86', 'name': 'Cielo Controle (Franquia)', 'group': 'Acerto/Cobrança', 'kind': 'ajustes' },
      { 'code': '90', 'name': 'Débito/crédito compensação de valores', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '91', 'name': 'Estorno debito/crédito de cessão', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '92', 'name': 'Estorno débito/crédito de gravame', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '93', 'name': 'Meliuz', 'group': 'Acerto/Cobrança', 'kind': 'ajustes' },
      { 'code': '94', 'name': 'Débito/crédito compensação cancelamento de transação em operação', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '95', 'name': 'Débito/crédito de penhora', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '96', 'name': 'Estorno de crédito/débito de penhora', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '97', 'name': 'Débito/crédito compensação cancelamento em operação', 'group': 'Acerto', 'kind': 'ajustes' },
      { 'code': '99', 'name': 'Tarifa por retentativa de transações (bandeiras)', 'group': 'Acerto', 'kind': 'ajustes' },
    ];
    result['bandeira'] = [
      { 'code': '001', 'name': 'VISA' },
      { 'code': '002', 'name': 'Mastercard' },
      { 'code': '003', 'name': 'Amex' },
      { 'code': '006', 'name': 'Sorocred' },
      { 'code': '007', 'name': 'ELO' },
      { 'code': '009', 'name': 'Diners' },
      { 'code': '011', 'name': 'Agiplan' },
      { 'code': '015', 'name': 'Banescard' },
      { 'code': '023', 'name': 'Cabal' },
      { 'code': '029', 'name': 'Credsystem' },
      { 'code': '035', 'name': 'Esplanada' },
      { 'code': '040', 'name': 'Hipercard' },
      { 'code': '060', 'name': 'JCB' },
      { 'code': '064', 'name': 'Credz' },
      { 'code': '072', 'name': 'Hiper' },
      { 'code': '075', 'name': 'Ourocard' },
    ];
    result['meio_captura'] = [
      { 'code': '00', 'name': 'LIO' },
      { 'code': '01', 'name': 'POS' },
      { 'code': '02', 'name': 'PDV ou TEF' },
      { 'code': '03', 'name': 'e-Commerce' },
      { 'code': '04', 'name': 'EDI' },
      { 'code': '05', 'name': 'ADP/BSP' },
      { 'code': '06', 'name': 'Manual' },
      { 'code': '07', 'name': 'URA/CVA' },
      { 'code': '08', 'name': 'Mobile' },
      { 'code': '09', 'name': 'Moedeiro Eletrônico em Rede' },
      { 'code': '99', 'name': 'Não identificado' },
    ];
    
    result['canal_venda'] = [
      { 'code': '000', 'name': 'LIO' },
      { 'code': '001', 'name': 'POS' },
      { 'code': '002', 'name': 'Mobile' },
      { 'code': '003', 'name': 'Manual' },
      { 'code': '004', 'name': 'URA/CVA' },
      { 'code': '005', 'name': 'EDI' },
      { 'code': '006', 'name': 'GDS/IATA' },
      { 'code': '007', 'name': 'e-Commerce' },
      { 'code': '008', 'name': 'PDV ou TEF' },
      { 'code': '009', 'name': 'Moedeiro Eletrônico em Rede' },
      { 'code': '010', 'name': 'Central (BackOffice)' },
      { 'code': '011', 'name': 'Central de atendimento' },
      { 'code': '012', 'name': 'Chargeback' },
      { 'code': '013', 'name': 'Ouvidoria' },
      { 'code': '014', 'name': 'Massivo' },
      { 'code': '015', 'name': 'Superlink/Digitado' },
      { 'code': '099', 'name': 'Não identificado' },
      { 'code': '998', 'name': 'Não se aplica' },
    ];
    
    result['ind_antecipacao'] = [
      { 'code': '', 'name': 'Não antecipado' } ,
      { 'code': 'A', 'name': 'Antecipado na Cielo ARV' } ,
      { 'code': 'C', 'name': 'Antecipado no banco Cessão de Recebíveis' } ,
    ];
    result['ind_revenda'] = [
      { 'code': 'R', 'name': 'Revenda' },
      { 'code': 'A', 'name': 'Aceleração' },
      { 'code': '', 'name': 'Nenhuma Ocorrência' },
    ];
    result['filler'] = [
      { 'code': '/', 'name': 'Vendas parceladas' },
      { 'code': 'A', 'name': 'Aceleração das parcelas' },
      { 'code': '', 'name': 'Demais situações' },
    ];
    result['modo_entrada_cartao'] = [
      { 'code': '00', 'name': 'Reentrada manual' },
      { 'code': '01', 'name': 'Digitada' },
      { 'code': '02', 'name': 'Trilha magnética' },
      { 'code': '03', 'name': 'Código de barra' },
      { 'code': '04', 'name': 'OCR (tecnologia que processa uma imagem e extrai os textos escritos)' },
      { 'code': '05', 'name': 'Chip online' },
      { 'code': '06', 'name': 'Trilha' },
      { 'code': '07', 'name': 'Contactless' },
      { 'code': '81', 'name': 'Digitada' },
      { 'code': '90', 'name': 'Trilha' },
      { 'code': '91', 'name': 'Contactless emulando tarja' },
      { 'code': '95', 'name': 'Chip offline' },
    ];
    result['']

    result['tipo_liquidacao'] = [
      { 'code': '000', 'name': 'Não identificado', 'kind': 'credito' },
      { 'code': '001', 'name': 'débito', 'kind': 'debito' },
      { 'code': '002', 'name': 'crédito', 'kind': 'credito' },
      { 'code': '004', 'name': 'voucher', 'kind': 'debito' }
    ];

    return result;
}

export const getIdTable = (property, value) => {
    const Tables = getTables();
    let findValue = _.find(Tables[property], { 'code': value });

    if (!findValue) {
        findValue = { 'code': value, 'name': value, 'group': '', 'kind': '' };
    }

    return findValue;
}
