import _ from 'lodash'


const getTables = () => {
    const result = {};

    result['transaction_status'] = [
        { 'code': '-3', 'name': 'Transaction before queue' },
        { 'code': '-2', 'name': 'New transaction' },
        { 'code': '-1', 'name': 'Validated transaction' },
        { 'code': '0', 'name': 'Transaction passed to payment' },
        { 'code': '1', 'name': 'Transaction new' },
        { 'code': '2', 'name': 'Payment cancelle' },
        { 'code': '3', 'name': 'Payment rejected' },
        { 'code': '4', 'name': 'Payment started' },
        { 'code': '5', 'name': 'Payment awaiting collection' },
        { 'code': '7', 'name': 'Payment returning to clien' },
        { 'code': '10', 'name': 'Payment accept requested' },
        { 'code': '12', 'name': 'Transaction cancel requested' },
        { 'code': '13', 'name': 'Payment reject requested' },
        { 'code': '17', 'name': 'Payment return requested' },
        { 'code': '99', 'name': 'Payment finished' },
        { 'code': '100', 'name': 'Tickets generated' },
        { 'code': '888', 'name': 'Payment error' },
    ];

    result['bought_product_status'] = [
        { 'code': '1', 'name': 'Active' },
        { 'code': '2', 'name': 'Cancelled' },
    ];

    result['bought_product_return_type'] = [
        { 'code': '1', 'name': 'Return' },
        { 'code': '2', 'name': 'Complaint' },
        { 'code': '3', 'name': 'Seat change' },
        { 'code': '4', 'name': 'User change' },
    ];

    result['bought_product_operation'] = [
        { 'code': '1', 'name': 'Buy' },
        { 'code': '2', 'name': 'Return' },
    ];

    result['clients_role'] = [
        { 'code': '2', 'name': 'Partner', },
        { 'code': '3', 'name': 'Fan', },
        { 'code': '4', 'name': 'Clerk', },
        { 'code': '10', 'name': 'Manager', },
        { 'code': '15', 'name': 'Admin', },
    ];

    result['payment_type'] = [
        { 'code': '1', 'name': 'PaymentOnline' },
        { 'code': '2', 'name': 'CashDesk' },
        { 'code': '4', 'name': 'Api' },
    ];

    result['payment_gate'] = [
        { 'code': '1', 'name': 'PayU' },
        { 'code': '2', 'name': 'P24' },
        { 'code': '3', 'name': 'EPay' },
        { 'code': '4', 'name': 'MobilePay' },
        { 'code': '5', 'name': 'Automaty' },
        { 'code': '6', 'name': 'Stripe' },
        { 'code': '7', 'name': 'Reservation' },
        { 'code': '8', 'name': 'Braintree' },
        { 'code': '9', 'name': 'Bambora' },
        { 'code': '10', 'name': 'Subscription' },
        { 'code': '11', 'name': 'Skytef' },
        { 'code': '12', 'name': 'Rede' },
        { 'code': '13', 'name': 'AndroidSmartPOS' },
        { 'code': '14', 'name': 'SagePay' },
        { 'code': '15', 'name': 'Vindi' },
    ];

    result['product_type'] = [
        { 'code': '10', 'name': 'Match', 'group': 'Tickets' },
        { 'code': '11', 'name': 'SeasonTicket', 'group': 'Tickets' },
        { 'code': '12', 'name': 'Merchandise', 'group': 'Merchandise' },
        { 'code': '13', 'name': 'Membership', 'group': 'Membership' },
        { 'code': '14', 'name': 'Hospitality', 'group': 'Merchandise' },
        { 'code': '15', 'name': 'Voucher', 'group': 'Merchandise' },
        { 'code': '16', 'name': 'SubscriptionReneval', 'group': 'Membership' },
        { 'code': '17', 'name': 'Card', 'group': 'Membership' },
        { 'code': '30', 'name': 'Return (Match)', 'group': 'Tickets' },
        { 'code': '31', 'name': 'Return (SeasonTicket)', 'group': 'Tickets' },
        { 'code': '32', 'name': 'Return (Voucher)', 'group': 'Merchandise' },
        { 'code': '33', 'name': 'Return (Merchandise)', 'group': 'Merchandise' },
        { 'code': '34', 'name': 'Return (Membership)', 'group': 'Membership' },
        { 'code': '35', 'name': 'Return (Hospitality)', 'group': 'Merchandise' },
        { 'code': '36', 'name': 'Return (SubscriptionReneval)', 'group': 'Membership' },
        { 'code': '37', 'name': 'Return (Card)', 'group': 'Membership' },
    ];

    result['skytef_cardbrand'] = [
        { 'code': '00000', 'name': 'BANDEIRA NAO DEFINIDA' },
        { 'code': '00001', 'name': 'VISA' },
        { 'code': '00002', 'name': 'MASTERCARD' },
        { 'code': '00003', 'name': 'DINERS' },
        { 'code': '00004', 'name': 'AMERICAN EXPRESS' },
        { 'code': '00005', 'name': 'SOLLO' },
        { 'code': '00006', 'name': 'SIDECARD (REDECARD)' },
        { 'code': '00007', 'name': 'PRIVATE LABEL (REDECARD)' },
        { 'code': '00008', 'name': 'REDESHOP' },
        { 'code': '00009', 'name': 'PAO DE ACUCAR' },
        { 'code': '00010', 'name': 'FININVEST (VISANET)' },
        { 'code': '00011', 'name': 'JCB' },
        { 'code': '00012', 'name': 'HIPERCARD' },
        { 'code': '00013', 'name': 'AURA' },
        { 'code': '00014', 'name': 'LOSANGO' },
        { 'code': '00015', 'name': 'SOROCRED' },
        { 'code': '00030', 'name': 'CABAL' },
        { 'code': '00031', 'name': 'ELO CREDITO' },
        { 'code': '00033', 'name': 'POLICARD' },
        { 'code': '00035', 'name': 'BANESCARD' },
        { 'code': '00038', 'name': 'CETELEM' },
        { 'code': '00041', 'name': 'SICREDI' },
        { 'code': '00043', 'name': 'COOPERCRED' },
        { 'code': '00045', 'name': 'A VISTA' },
        { 'code': '00057', 'name': 'CREDISYSTEM (MAIS)' },
        { 'code': '00058', 'name': 'BANPARA' },
        { 'code': '00060', 'name': 'AMAZONCARD' },
        { 'code': '00061', 'name': 'YAMADA' },
        { 'code': '00062', 'name': 'GOIASCARD' },
        { 'code': '00063', 'name': 'CREDPAR' },
        { 'code': '00064', 'name': 'BOTICARIO' },
        { 'code': '00065', 'name': 'ASCARD' },
        { 'code': '00066', 'name': 'JETPAR' },
        { 'code': '00067', 'name': 'MAXXCARD' },
        { 'code': '00068', 'name': 'GARANTIDO' },
        { 'code': '00069', 'name': 'AMAZON PRIME' },
        { 'code': '00070', 'name': 'CREDZ' },
        { 'code': '00071', 'name': 'CREDISHOP' },
        { 'code': '00073', 'name': 'LIBERCARD' },
        { 'code': '00078', 'name': 'PEELA' },
        { 'code': '00084', 'name': 'BANRISUL' },
        { 'code': '00086', 'name': 'VERDECARD' },
        { 'code': '00087', 'name': 'REFEISUL' },
        { 'code': '00090', 'name': 'CALCARD' },
        { 'code': '00091', 'name': 'BANESE' },
        { 'code': '00093', 'name': 'TRICARD' },
        { 'code': '00094', 'name': 'TRICARD' },
        { 'code': '00095', 'name': 'APOLO CARD' },
        { 'code': '00096', 'name': 'GLOBAL COOPER' },
        { 'code': '00097', 'name': 'PRA TI' },
        { 'code': '00098', 'name': 'SUPPERCARD' },
        { 'code': '00099', 'name': 'QUALITA CARD' },
        { 'code': '00101', 'name': 'TECBIZ' },
        { 'code': '00102', 'name': 'TODO' },
        { 'code': '00104', 'name': 'VECELL CARD' },
        { 'code': '00105', 'name': 'MAXXVAN' },
        { 'code': '00107', 'name': 'ACCENTIV' },
        { 'code': '00108', 'name': 'ASPEB' },
        { 'code': '00109', 'name': 'VALE EXPRESS' },
        { 'code': '00114', 'name': 'DAYCARD' },
        { 'code': '00118', 'name': 'RVCARDS' },
        { 'code': '00119', 'name': 'LEADER' },
        { 'code': '00121', 'name': 'TELENET' },
        { 'code': '00124', 'name': 'TICKETLOG' },
        { 'code': '00127', 'name': 'SOFTNEX' },
        { 'code': '00130', 'name': 'GOODCARD' },
        { 'code': '00131', 'name': 'PAGSIMPLES' },
        { 'code': '00132', 'name': 'ICARDS' },
        { 'code': '00137', 'name': 'FORTBRASIL' },
        { 'code': '00138', 'name': 'VOXCRED' },
        { 'code': '00140', 'name': 'BORBANET' },
        { 'code': '00141', 'name': 'VEGASCARD' },
        { 'code': '00142', 'name': 'BIGCARD' },
        { 'code': '00143', 'name': 'BONUSCRED' },
        { 'code': '00144', 'name': 'BRASILCARD' },
        { 'code': '00145', 'name': 'CONVENIOS CARD' },
        { 'code': '00146', 'name': 'COOPERCARD' },
        { 'code': '00147', 'name': 'DIAMANTECARD' },
        { 'code': '00148', 'name': 'FORTCARD' },
        { 'code': '00149', 'name': 'JETCARD' },
        { 'code': '00150', 'name': 'ONECARD' },
        { 'code': '00151', 'name': 'PERSONALCARD' },
        { 'code': '00152', 'name': 'SYSTEMFARMA' },
        { 'code': '00153', 'name': 'LIV' },
        { 'code': '00154', 'name': 'UP' },
        { 'code': '00155', 'name': 'COOPELIFE' },
        { 'code': '10001', 'name': 'TICKET' },
        { 'code': '10002', 'name': 'VISA VALE' },
        { 'code': '10003', 'name': 'SODEXO' },
        { 'code': '10004', 'name': 'NUTRICASH' },
        { 'code': '10005', 'name': 'GREENCARD' },
        { 'code': '10006', 'name': 'PLANVALE' },
        { 'code': '10007', 'name': 'BANQUET' },
        { 'code': '10008', 'name': 'VEROCHEQUE' },
        { 'code': '10009', 'name': 'SAPORE' },
        { 'code': '10010', 'name': 'BNB CLUBE' },
        { 'code': '10011', 'name': 'VALECARD' },
        { 'code': '10012', 'name': 'CABAL VOUCHER' },
        { 'code': '10013', 'name': 'ELO' },
        { 'code': '10014', 'name': 'DISCOVERY' },
        { 'code': '10015', 'name': 'GOODCARD' },
        { 'code': '10016', 'name': 'POLICARD' },
        { 'code': '10017', 'name': 'CARDSYSTEM' },
        { 'code': '10018', 'name': 'BONUS CBA' },
        { 'code': '10019', 'name': 'ALELO' },
        { 'code': '10020', 'name': 'BANESCARD' },
        { 'code': '10021', 'name': 'ALELO' },
        { 'code': '10022', 'name': 'ALELO' },
        { 'code': '10023', 'name': 'ALELO' },
        { 'code': '10024', 'name': 'TICKET' },
        { 'code': '10025', 'name': 'TICKET' },
        { 'code': '10026', 'name': 'TICKET' },
        { 'code': '10027', 'name': 'TICKET' },
        { 'code': '10028', 'name': 'SODEXO' },
        { 'code': '10029', 'name': 'SODEXO' },
        { 'code': '10030', 'name': 'SODEXO' },
        { 'code': '10031', 'name': 'SODEXO' },
        { 'code': '10032', 'name': 'SODEXO' },
        { 'code': '10033', 'name': 'SODEXO' },
        { 'code': '10037', 'name': 'SOROCRED' },
        { 'code': '10039', 'name': 'VALEMULTI' },
        { 'code': '10040', 'name': 'VALEFROTA' },
        { 'code': '10044', 'name': 'COOPERCRED' },
        { 'code': '10046', 'name': 'VALEFACIL' },
        { 'code': '10047', 'name': 'VR' },
        { 'code': '10048', 'name': 'VR' },
        { 'code': '10049', 'name': 'VR' },
        { 'code': '10050', 'name': 'VR' },
        { 'code': '10051', 'name': 'PLANVALE' },
        { 'code': '10052', 'name': 'BANRISUL' },
        { 'code': '10053', 'name': 'NUTRICASH' },
        { 'code': '10054', 'name': 'TICKET' },
        { 'code': '10055', 'name': 'VALECARD' },
        { 'code': '10056', 'name': 'COOPERCRED' },
        { 'code': '10070', 'name': 'VR' },
        { 'code': '10071', 'name': 'PLANVALE' },
        { 'code': '10072', 'name': 'PLANVALE' },
        { 'code': '10073', 'name': 'PLANVALE' },
        { 'code': '10074', 'name': 'PLANVALE' },
        { 'code': '10075', 'name': 'PLANVALE' },
        { 'code': '10076', 'name': 'PEELA' },
        { 'code': '10077', 'name': 'LIBERCARD' },
        { 'code': '10079', 'name': 'UP' },
        { 'code': '10080', 'name': 'UP' },
        { 'code': '10081', 'name': 'UP' },
        { 'code': '10082', 'name': 'ELO' },
        { 'code': '10083', 'name': 'VR' },
        { 'code': '10088', 'name': 'REFEISUL' },
        { 'code': '10089', 'name': 'REFEISUL' },
        { 'code': '10090', 'name': 'VEROCHEQUE' },
        { 'code': '10100', 'name': 'QUALITA CARD' },
        { 'code': '10103', 'name': 'TODO' },
        { 'code': '10110', 'name': 'VALE EXPRESS' },
        { 'code': '10112', 'name': 'GOLDICARD' },
        { 'code': '10113', 'name': 'FLEETCARD' },
        { 'code': '10116', 'name': 'HUBPREPAID' },
        { 'code': '10117', 'name': 'FLEXFROTA' },
        { 'code': '10122', 'name': 'TELENET' },
        { 'code': '10123', 'name': 'TELENET' },
        { 'code': '10125', 'name': 'TICKETLOG' },
        { 'code': '10129', 'name': 'SOFTNEX' },
        { 'code': '10132', 'name': 'GOODCARD' },
        { 'code': '10133', 'name': 'GOODCARD' },
        { 'code': '10134', 'name': 'GOODCARD' },
        { 'code': '10135', 'name': 'GOODCARD' },
        { 'code': '10136', 'name': 'VELOE' },
        { 'code': '10137', 'name': 'COOPERCRED' },
        { 'code': '10138', 'name': 'COOPERCRED' },
        { 'code': '10139', 'name': 'WIZEO' },
        { 'code': '10140', 'name': 'BEN VISAVALE' },
        { 'code': '10141', 'name': 'BEN VISAVALE' },
        { 'code': '10142', 'name': 'ABRAPETITE' },
        { 'code': '10143', 'name': 'AVANCARD' },
        { 'code': '10144', 'name': 'BIQ' },
        { 'code': '10145', 'name': 'BONUSCRED' },
        { 'code': '10146', 'name': 'BRASILCARD' },
        { 'code': '10147', 'name': 'CONVENIOS CARD' },
        { 'code': '10148', 'name': 'COOPERCARD' },
        { 'code': '10149', 'name': 'CREDIALIMENTACAO' },
        { 'code': '10150', 'name': 'EUCARD' },
        { 'code': '10151', 'name': 'FACECARD' },
        { 'code': '10152', 'name': 'FLEETCARD' },
        { 'code': '10153', 'name': 'LECARD' },
        { 'code': '10154', 'name': 'NUTRICARD' },
        { 'code': '10155', 'name': 'SENFF' },
        { 'code': '10156', 'name': 'SINDPLUS' },
        { 'code': '10157', 'name': 'USECRED' },
        { 'code': '10158', 'name': 'VALESHOP' },
        { 'code': '10159', 'name': 'VEGASCARD' },
        { 'code': '10160', 'name': 'VSCARD' },
        { 'code': '10161', 'name': 'ROTACARD' },
        { 'code': '10162', 'name': 'UP' },
        { 'code': '10163', 'name': 'UP' },
        { 'code': '10164', 'name': 'UP' },
        { 'code': '10165', 'name': 'UP' },
        { 'code': '10166', 'name': 'UP' },
        { 'code': '10167', 'name': 'UP' },
        { 'code': '20001', 'name': 'MAESTRO' },
        { 'code': '20002', 'name': 'VISA ELECTRON' },
        { 'code': '20003', 'name': 'CABAL DEBITO' },
        { 'code': '20012', 'name': 'CABAL DEBITO' },
        { 'code': '20013', 'name': 'ELO' },
        { 'code': '20032', 'name': 'ELO DEBITO' },
        { 'code': '20034', 'name': 'POLICARD' },
        { 'code': '20036', 'name': 'BANESCARD' },
        { 'code': '20037', 'name': 'HIPERCARD' },
        { 'code': '20042', 'name': 'SICREDI' },
        { 'code': '20059', 'name': 'BANPARA' },
        { 'code': '20071', 'name': 'SOROCRED' },
        { 'code': '20072', 'name': 'MAXXICARD' },
        { 'code': '20073', 'name': 'MAXXICARD' },
        { 'code': '20074', 'name': 'MAXXICARD' },
        { 'code': '20075', 'name': 'MAXXICARD' },
        { 'code': '20085', 'name': 'BANRISUL' },
        { 'code': '20092', 'name': 'BANESE' },
        { 'code': '20106', 'name': 'MAXXVAN' },
        { 'code': '20111', 'name': 'VALE EXPRESS' },
        { 'code': '20115', 'name': 'DAYCARD' },
        { 'code': '20120', 'name': 'CONVENIO FACIL' },
        { 'code': '20126', 'name': 'TICKETLOG' },
        { 'code': '20128', 'name': 'SOFTNEX' },
        { 'code': '20131', 'name': 'GOODCARD' },
        { 'code': '20132', 'name': 'COOPERCRED' },
        { 'code': '20133', 'name': 'VEGASCARD' },
        { 'code': '20134', 'name': 'LIV' },
        { 'code': '20135', 'name': 'UP' },
        { 'code': '20136', 'name': 'COOPELIFE' },
        { 'code': '20137', 'name': 'TELENET' },
    ];

    return result;
}

const getIdTable = (property, value, field) => {
    let filter = {};
    filter[field] = _.trim(String(value));

    const Tables = getTables();
    let findValue = _.find(Tables[property], filter);

    if (!findValue) {
        findValue = { 'code': value, 'name': value, 'group': 'not-found' };
    }

    return findValue;
}

export const getTableByCode = (property, value) => {
    return getIdTable(property, value, 'code');
}

export const getTableByName = (property, value) => {
    return getIdTable(property, value, 'name');
}

export const getDescriptionByCode = (property, value) => {
    let content = getIdTable(property, value, 'code'),
        name = _.get(content, 'name', ''),
        result = '';
    if (_.isEmpty(name) == false) {
        result = name;
    }
    if (name == undefined) {
        result = '';
    }
    return result;
}
