
export {default as cldr_files} from 'app/models/mongodb/skill/files'
export {default as cldr_pos_config} from 'app/models/mongodb/skill/pos-config'

export {default as cldr_maxipago_daily} from 'app/models/mongodb/maxipago/daily'

export {default as cldr_bradesco_extrato_record0} from 'app/models/mongodb/bradesco/extrato/record0'
export {default as cldr_bradesco_extrato_record1} from 'app/models/mongodb/bradesco/extrato/record1'
export {default as cldr_bradesco_extrato_record3} from 'app/models/mongodb/bradesco/extrato/record3'
export {default as cldr_bradesco_extrato_record5} from 'app/models/mongodb/bradesco/extrato/record5'
export {default as cldr_bradesco_extrato_record9} from 'app/models/mongodb/bradesco/extrato/record9'

export {default as cldr_cielo_antecipacao_record0} from 'app/models/mongodb/cielo/antecipacao/record0'
export {default as cldr_cielo_antecipacao_record2} from 'app/models/mongodb/cielo/antecipacao/record2'
export {default as cldr_cielo_antecipacao_record5} from 'app/models/mongodb/cielo/antecipacao/record5'
export {default as cldr_cielo_antecipacao_record6} from 'app/models/mongodb/cielo/antecipacao/record6'
export {default as cldr_cielo_antecipacao_record7} from 'app/models/mongodb/cielo/antecipacao/record7'
export {default as cldr_cielo_antecipacao_record9} from 'app/models/mongodb/cielo/antecipacao/record9'
export {default as cldr_cielo_antecipacao_recordX} from 'app/models/mongodb/cielo/antecipacao/recordX'
export {default as cldr_cielo_pagamentos_record0} from 'app/models/mongodb/cielo/pagamentos/record0'
export {default as cldr_cielo_pagamentos_record1} from 'app/models/mongodb/cielo/pagamentos/record1'
export {default as cldr_cielo_pagamentos_record2} from 'app/models/mongodb/cielo/pagamentos/record2'
export {default as cldr_cielo_pagamentos_record9} from 'app/models/mongodb/cielo/pagamentos/record9'
export {default as cldr_cielo_pagamentos_recordX} from 'app/models/mongodb/cielo/pagamentos/recordX'
export {default as cldr_cielo_saldos_record0} from 'app/models/mongodb/cielo/saldos/record0'
export {default as cldr_cielo_saldos_record1} from 'app/models/mongodb/cielo/saldos/record1'
export {default as cldr_cielo_saldos_record9} from 'app/models/mongodb/cielo/saldos/record9'
export {default as cldr_cielo_saldos_recordX} from 'app/models/mongodb/cielo/saldos/recordX'
export {default as cldr_cielo_vendas_record0} from 'app/models/mongodb/cielo/vendas/record0'
export {default as cldr_cielo_vendas_record1} from 'app/models/mongodb/cielo/vendas/record1'
export {default as cldr_cielo_vendas_record2} from 'app/models/mongodb/cielo/vendas/record2'
export {default as cldr_cielo_vendas_record9} from 'app/models/mongodb/cielo/vendas/record9'
export {default as cldr_cielo_vendas_recordX} from 'app/models/mongodb/cielo/vendas/recordX'

export {default as cldr_itau_extrato} from 'app/models/mongodb/itau/extrato/genneral'
export {default as cldr_itau_extrato_record0} from 'app/models/mongodb/itau/extrato/record0'
export {default as cldr_itau_extrato_record1} from 'app/models/mongodb/itau/extrato/record1'
export {default as cldr_itau_extrato_record3} from 'app/models/mongodb/itau/extrato/record3'
export {default as cldr_itau_extrato_record5} from 'app/models/mongodb/itau/extrato/record5'
export {default as cldr_itau_extrato_record9} from 'app/models/mongodb/itau/extrato/record9'

export {default as cldr_itau_boleto_record0} from 'app/models/mongodb/itau/boleto/record0'
export {default as cldr_itau_boleto_record1} from 'app/models/mongodb/itau/boleto/record1'
export {default as cldr_itau_boleto_record9} from 'app/models/mongodb/itau/boleto/record9'

export {default as cldr_itau_debito_record0} from 'app/models/mongodb/itau/debito/record0'
export {default as cldr_itau_debito_record1} from 'app/models/mongodb/itau/debito/record1'
export {default as cldr_itau_debito_record3} from 'app/models/mongodb/itau/debito/record3'
export {default as cldr_itau_debito_record5} from 'app/models/mongodb/itau/debito/record5'
export {default as cldr_itau_debito_record9} from 'app/models/mongodb/itau/debito/record9'
export {default as cldr_itau_debito_recordA} from 'app/models/mongodb/itau/debito/recordA'
export {default as cldr_itau_debito_recordB} from 'app/models/mongodb/itau/debito/recordB'
export {default as cldr_itau_debito_recordF} from 'app/models/mongodb/itau/debito/recordF'
export {default as cldr_itau_debito_recordH} from 'app/models/mongodb/itau/debito/recordH'
export {default as cldr_itau_debito_recordZ} from 'app/models/mongodb/itau/debito/recordZ'

export {default as cldr_rede_credito_genneral} from 'app/models/mongodb/rede/credito/genneral'
export {default as cldr_rede_credito_record002} from 'app/models/mongodb/rede/credito/record002'
export {default as cldr_rede_credito_record004} from 'app/models/mongodb/rede/credito/record004'
export {default as cldr_rede_credito_record005} from 'app/models/mongodb/rede/credito/record005'
export {default as cldr_rede_credito_record033} from 'app/models/mongodb/rede/credito/record033'
export {default as cldr_rede_credito_record006} from 'app/models/mongodb/rede/credito/record006'
export {default as cldr_rede_credito_record008} from 'app/models/mongodb/rede/credito/record008'
export {default as cldr_rede_credito_record034} from 'app/models/mongodb/rede/credito/record034'
export {default as cldr_rede_credito_record010} from 'app/models/mongodb/rede/credito/record010'
export {default as cldr_rede_credito_record012} from 'app/models/mongodb/rede/credito/record012'
export {default as cldr_rede_credito_record035} from 'app/models/mongodb/rede/credito/record035'
export {default as cldr_rede_credito_record014} from 'app/models/mongodb/rede/credito/record014'
export {default as cldr_rede_credito_record026} from 'app/models/mongodb/rede/credito/record026'
export {default as cldr_rede_credito_record028} from 'app/models/mongodb/rede/credito/record028'
export {default as cldr_rede_debito_record00} from 'app/models/mongodb/rede/debito/record00'
export {default as cldr_rede_debito_record01} from 'app/models/mongodb/rede/debito/record01'
export {default as cldr_rede_debito_record02} from 'app/models/mongodb/rede/debito/record02'
export {default as cldr_rede_debito_record03} from 'app/models/mongodb/rede/debito/record03'
export {default as cldr_rede_debito_record04} from 'app/models/mongodb/rede/debito/record04'
export {default as cldr_rede_debito_record05} from 'app/models/mongodb/rede/debito/record05'
export {default as cldr_rede_debito_record11} from 'app/models/mongodb/rede/debito/record11'
export {default as cldr_rede_debito_record13} from 'app/models/mongodb/rede/debito/record13'
export {default as cldr_rede_debito_record17} from 'app/models/mongodb/rede/debito/record17'
export {default as cldr_rede_financeiro_genneral} from 'app/models/mongodb/rede/financeiro/genneral'
export {default as cldr_rede_financeiro_record030} from 'app/models/mongodb/rede/financeiro/record030'
export {default as cldr_rede_financeiro_record032} from 'app/models/mongodb/rede/financeiro/record032'
export {default as cldr_rede_financeiro_record034} from 'app/models/mongodb/rede/financeiro/record034'
export {default as cldr_rede_financeiro_record035} from 'app/models/mongodb/rede/financeiro/record035'
export {default as cldr_rede_financeiro_record053} from 'app/models/mongodb/rede/financeiro/record053'
export {default as cldr_rede_financeiro_record036} from 'app/models/mongodb/rede/financeiro/record036'
export {default as cldr_rede_financeiro_record037} from 'app/models/mongodb/rede/financeiro/record037'
export {default as cldr_rede_financeiro_record038} from 'app/models/mongodb/rede/financeiro/record038'
export {default as cldr_rede_financeiro_record054} from 'app/models/mongodb/rede/financeiro/record054'
export {default as cldr_rede_financeiro_record043} from 'app/models/mongodb/rede/financeiro/record043'
export {default as cldr_rede_financeiro_record044} from 'app/models/mongodb/rede/financeiro/record044'
export {default as cldr_rede_financeiro_record055} from 'app/models/mongodb/rede/financeiro/record055'
export {default as cldr_rede_financeiro_record045} from 'app/models/mongodb/rede/financeiro/record045'
export {default as cldr_rede_financeiro_record056} from 'app/models/mongodb/rede/financeiro/record056'
export {default as cldr_rede_financeiro_record049} from 'app/models/mongodb/rede/financeiro/record049'
export {default as cldr_rede_financeiro_record057} from 'app/models/mongodb/rede/financeiro/record057'
export {default as cldr_rede_financeiro_record050} from 'app/models/mongodb/rede/financeiro/record050'
export {default as cldr_rede_financeiro_record052} from 'app/models/mongodb/rede/financeiro/record052'
export {default as cldr_rede_financeiro_record999} from 'app/models/mongodb/rede/financeiro/record999'
export {default as cldr_rede_saldos_record060} from 'app/models/mongodb/rede/saldos/record060'
export {default as cldr_rede_saldos_record061} from 'app/models/mongodb/rede/saldos/record061'
export {default as cldr_rede_saldos_record062} from 'app/models/mongodb/rede/saldos/record062'
export {default as cldr_rede_saldos_record066} from 'app/models/mongodb/rede/saldos/record066'
export {default as cldr_rede_saldos_record068} from 'app/models/mongodb/rede/saldos/record068'

export {default as sales_vindi_products} from 'app/models/mongodb/vindi/products'
export {default as sales_vindi_customers} from 'app/models/mongodb/vindi/customers'
export {default as sales_vindi_bills} from 'app/models/mongodb/vindi/bills'
export {default as sales_vindi_transactions} from 'app/models/mongodb/vindi/transactions'
export {default as sales_vindi_issues} from 'app/models/mongodb/vindi/issues'
export {default as sales_vindi_events} from 'app/models/mongodb/vindi/events'

export {default as sales_newc_clients} from 'app/models/mongodb/newc/clients'
export {default as sales_newc_products} from 'app/models/mongodb/newc/products'
export {default as sales_newc_transactions} from 'app/models/mongodb/newc/transactions'

export {default as sales_multiclubes_sales} from 'app/models/mongodb/multiclubes/sales'
export {default as sales_multiclubes_payments} from 'app/models/mongodb/multiclubes/payments'

